import type { CefrLevel } from '../resume/resumeTypes';

export const MONTHS_RU: Record<string, string> = {
  январь: '01',
  января: '01',
  февраль: '02',
  февраля: '02',
  март: '03',
  марта: '03',
  апрель: '04',
  апреля: '04',
  май: '05',
  мая: '05',
  июнь: '06',
  июня: '06',
  июль: '07',
  июля: '07',
  август: '08',
  августа: '08',
  сентябрь: '09',
  сентября: '09',
  октябрь: '10',
  октября: '10',
  ноябрь: '11',
  ноября: '11',
  декабрь: '12',
  декабря: '12',
};

export const MONTHS_EN: Record<string, string> = {
  january: '01',
  jan: '01',
  february: '02',
  feb: '02',
  march: '03',
  mar: '03',
  april: '04',
  apr: '04',
  may: '05',
  june: '06',
  jun: '06',
  july: '07',
  jul: '07',
  august: '08',
  aug: '08',
  september: '09',
  sep: '09',
  sept: '09',
  october: '10',
  oct: '10',
  november: '11',
  nov: '11',
  december: '12',
  dec: '12',
};

export const CEFR_MAP: Record<string, CefrLevel> = {
  a1: 'A1',
  a2: 'A2',
  b1: 'B1',
  b2: 'B2',
  c1: 'C1',
  c2: 'C2',
  начальный: 'A1',
  базовый: 'A2',
  средний: 'B1',
  выше_среднего: 'B2',
  продвинутый: 'C1',
  свободно: 'C2',
  родной: 'C2',
  native: 'C2',
  bilingual: 'C2',
  fluent: 'C1',
  full_professional: 'C2',
  professional_working: 'C1',
  limited_working: 'B1',
  elementary: 'A2',
  intermediate: 'B1',
  upper_intermediate: 'B2',
  advanced: 'C1',
};

export const SECTION_DELIMITERS = [
  'Опыт работы',
  'Experience',
  'Work Experience',
  'Professional Experience',
  'Высшее образование',
  'Образование',
  'Education',
  'Ключевые навыки',
  'Навыки',
  'Top Skills',
  'Skills',
  'Электронные сертификаты',
  'Сертификаты',
  'Certifications',
  'Курсы',
  'Courses',
  'Повышение квалификации',
  'Тесты, экзамены',
  'Тестирования',
  'Тесты',
  'Tests',
  'Tests & Exams',
  'Assessments',
  'Рекомендации',
  'Recommendations',
  'References',
  'Знание языков',
  'Языки',
  'Languages',
  'Summary',
  'Executive Summary',
  'О себе',
  'Обо мне',
  'About me',
  'About',
  'Honors-Awards',
  'Honors & Awards',
  'Publications',
  'Patents',
  'График работы',
  'Гражданство',
  'Contact',
];

export function sectionLookahead(current: string): string {
  const others = SECTION_DELIMITERS.filter((d) => d.toLowerCase() !== current.toLowerCase());
  return `(?=\\n+(?:${others.join('|')}|$))`;
}
