import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    exclude: ['**/prototypes/**', '**/node_modules/**', '**/dist/**'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'html'],
      reportsDirectory: 'coverage',
      include: [
        'src/services/*.ts',
        'src/features/evidence/evidenceEngine.ts',
        'src/features/diagnostic/careerDiagnostic.ts',
        'src/features/career-map/roleMarketMap.ts',
        'src/features/next-action/careerActionPolicy.ts',
        'src/features/opportunity/opportunityEngine.ts',
        'src/features/workspace/workspaceStorage.ts',
        'src/features/workspace/linkedinArchive.ts',
        'src/features/workspace/pdfDocumentClassifier.ts',
        'src/features/workspace/pdfInspector.ts',
        'src/features/workspace/pdfInspectorClient.ts',
        'src/features/workspace/pdfResume.ts',
        'src/features/workspace/profileIngestion.ts',
        'src/features/connections/connectionResult.ts',
        'src/features/connections/connectionState.ts',
        'server/config.ts',
        'server/auth/authService.ts',
        'server/data/sealedText.ts',
        'server/data/sqliteCandidateStore.ts',
        'server/domain/coach.ts',
        'server/prompts/careerSuperPrompt.ts',
        'server/connectors/connectorHarness.ts',
        'server/connectors/connectorActionQueue.ts',
        'server/connectors/hostedApplicationBrowser.ts',
        'server/connectors/jobPostingParser.ts',
        'server/connectors/oauthConnector.ts',
        'server/connectors/officialOAuthTransport.ts',
        'server/providers/openAICoachProvider.ts',
        'server/providers/openRouterCoachProvider.ts',
        'server/providers/openAICompatibleCoachProvider.ts',
        'server/providers/nativeCoachProvider.ts',
        'server/providers/coachProviderFactory.ts',
        'server/providers/modelRegistry.ts',
        'server/providers/privacyAwareCoachProvider.ts',
      ],
      thresholds: {
        branches: 80,
        functions: 80,
        lines: 80,
        statements: 80,
      },
    },
  },
});
