import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    exclude: [
      '**/e2e/**',
      // Agent worktrees hold a second checkout of this repo; running their
      // copy of the suite doubles every count and reports on code that is not
      // in this tree.
      '**/.claude/worktrees/**',
      '**/prototypes/**',
      '**/node_modules/**',
      '**/dist/**',
    ],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'html'],
      reportsDirectory: 'coverage',
      include: [
        'shared/*.ts',
        'src/services/*.ts',
        'src/features/evidence/evidenceEngine.ts',
        'src/features/diagnostic/careerDiagnostic.ts',
        'src/features/career-map/roleMarketMap.ts',
        'src/features/next-action/careerActionPolicy.ts',
        'src/features/opportunity/opportunityEngine.ts',
        'src/features/cabinet/routePremises.ts',
        'src/features/legal/legalStructuredData.ts',
        'server/connectors/vacancyRelevance.ts',
        'server/vacancies/jsonSourceAdapters.ts',
        'server/vacancies/defaultVacancySources.ts',
        'server/connectors/feedText.ts',
        'server/connectors/telegramJobHeader.ts',
        'server/connectors/telegramPostType.ts',
        'shared/employerLabel.ts',
        'server/vacancies/multiSourceVacancyEngine.ts',
        'server/vacancies/sourceHealthVerdict.ts',
        'server/vacancies/adminVacancyPage.ts',
        'server/data/documentTextPage.ts',
        'server/domain/dataRetention.ts',
        'server/domain/company.ts',
        'server/domain/geoCoordinates.ts',
        'server/domain/companyListIngestion.ts',
        'server/domain/companyRegistry.ts',
        'server/routes/companiesRoute.ts',
        'server/auth/legalConsentStore.ts',
        'server/routes/rateLimitMessage.ts',
        'src/features/shell/buildFreshness.ts',
        'src/features/shell/releaseSha.ts',
        'server/vacancies/sqliteVacancyPoolStore.ts',
        'src/features/workspace/workspaceStorage.ts',
        'src/features/workspace/candidateRegions.ts',
        'src/features/workspace/linkedinArchive.ts',
        'src/features/workspace/pdfDocumentClassifier.ts',
        'src/features/workspace/pdfInspector.ts',
        'src/features/workspace/pdfInspectorClient.ts',
        'src/features/workspace/pdfResume.ts',
        'src/features/workspace/profileIngestion.ts',
        'src/features/workspace/resumeSourceText.ts',
        'src/features/connections/connectionResult.ts',
        'src/features/connections/connectorSession.ts',
        'src/features/connections/connectionState.ts',
        'src/features/connections/hhSessionPoll.ts',
        'src/features/connections/linkedinSessionPoll.ts',
        'src/features/connections/sessionCapture.ts',
        'src/features/connections/sessionWaitingStage.ts',
        'src/features/connections/connectorSessionStart.ts',
        'src/features/connections/linkedinProtectedRoute.ts',
        'src/features/journey/connectedProfileSource.ts',
        'src/features/resume/resumeStudioModel.ts',
        'src/features/resume/resumeDocumentRows.ts',
        'src/features/resume/resumeLabels.ts',
        'server/domain/candidateWorkspace.ts',
        'server/config.ts',
        'server/auth/authService.ts',
        'server/data/sealedText.ts',
        'server/data/sqliteCandidateStore.ts',
        'server/domain/coach.ts',
        'server/domain/resumeStudio.ts',
        'server/domain/resumeDraft.ts',
        'server/domain/resumeEvidenceEligibility.ts',
        'server/domain/resumeImport.ts',
        'server/domain/resumeStructuring.ts',
        'server/providers/resumeStructurer.ts',
        'server/localEnvironmentFile.ts',
        'server/data/sqliteResumeRepository.ts',
        'server/prompts/careerSuperPrompt.ts',
        'server/connectors/connectorHarness.ts',
        'server/connectors/connectorActionQueue.ts',
        'server/connectors/careerCommandConnectorRouter.ts',
        'server/connectors/hh/hhConnector.ts',
        'server/connectors/hh/hhApplicationBrowser.ts',
        'server/connectors/hh/connectorInspectionScript.ts',
        'server/connectors/hh/hhBrowserLogin.ts',
        'server/connectors/hh/hhResumeInventory.ts',
        'server/connectors/hh/hhTestAccountEnvironment.ts',
        'server/connectors/hostedApplicationBrowser.ts',
        'server/connectors/jobPostingParser.ts',
        'server/connectors/oauthConnector.ts',
        'server/connectors/officialOAuthTransport.ts',
        'server/providers/openAICoachProvider.ts',
        'server/providers/openRouterCoachProvider.ts',
        'server/providers/openAICompatibleCoachProvider.ts',
        'server/providers/nativeCoachProvider.ts',
        'server/providers/coachProviderFactory.ts',
        'server/providers/modelRegistry.ts',
        'server/providers/privacyAwareCoachProvider.ts',
      ],
      thresholds: {
        branches: 80,
        functions: 80,
        lines: 80,
        statements: 80,
      },
    },
  },
});
