// @vitest-environment jsdom
import { act } from 'react-dom/test-utils';
import { createRoot, type Root } from 'react-dom/client';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { useResumeIngestion } from './useResumeIngestion';
import { OnboardingWizard } from './OnboardingWizard';
import { getCandidateCampaign, rebuildCandidateCampaignRoles } from '../coach/matchedVacancyApi';
import { putCandidateWorkspace } from '../coach/coachApi';
import { parseResumeContent, parsedResumeToDraft } from '../workspace/resumeParser';
import type { CampaignMetaView } from '../coach/matchedVacancyApi';
import type { ResumeIngestionState } from './useResumeIngestion';

vi.mock('./useResumeIngestion', () => ({ useResumeIngestion: vi.fn() }));

vi.mock('../coach/coachApi', async () => {
  const actual = await vi.importActual<typeof import('../coach/coachApi')>('../coach/coachApi');
  return { ...actual, putCandidateWorkspace: vi.fn() };
});

vi.mock('../coach/matchedVacancyApi', async () => {
  const actual = await vi.importActual<typeof import('../coach/matchedVacancyApi')>(
    '../coach/matchedVacancyApi',
  );
  return {
    ...actual,
    getCandidateCampaign: vi.fn(),
    rebuildCandidateCampaignRoles: vi.fn(),
    saveCandidateCampaign: vi.fn(),
  };
});

describe('OnboardingWizard campaign lifecycle', () => {
  let container: HTMLDivElement;
  let root: Root;
  let readCalls = 0;
  let wasUnmounted = false;
  const pollSignals: AbortSignal[] = [];
  const staleCampaign: CampaignMetaView = {
    roles: { value: ['VP of Engineering'], origin: 'model' },
    regions: { value: [], origin: 'model' },
    autoGeneratedAt: 'before-rebuild',
    autoRoles: [
      {
        id: 'vp-eng',
        title: 'VP of Engineering',
        titleRu: 'Вице-президент по инженерии',
        level: 'vp',
        kind: 'primary',
        reason: 'Опыт управления инженерией.',
        evidenceRefs: [],
        evidence: [],
      },
    ],
  };

  function clickButton(label: string) {
    const button = [...container.querySelectorAll<HTMLButtonElement>('button')].find((entry) =>
      entry.textContent?.includes(label),
    );
    if (!button) throw new Error(`button not found: ${label}`);
    button.click();
  }

  async function advanceToCampaign(expectedPolls: number) {
    await act(async () => clickButton('Продолжить'));
    await act(async () => clickButton('Продолжить'));
    await act(async () => clickButton('Продолжить'));
    await act(async () => {
      for (let i = 0; i < 40 && pollSignals.length < expectedPolls; i += 1) {
        await Promise.resolve();
      }
    });
  }

  beforeEach(() => {
    container = document.createElement('div');
    root = createRoot(container);
    pollSignals.length = 0;
    readCalls = 0;
    wasUnmounted = false;
    const parsed = parseResumeContent(`Alex Example\nVP of Engineering\n\nExperience\n2022 — настоящее время\nExample Inc.\nVP of Engineering\nРуководил инженерной командой.`);
    vi.mocked(useResumeIngestion).mockReturnValue({
      result: {
        parsed,
        draft: parsedResumeToDraft(parsed),
        text: parsed.rawText,
        source: 'pdf',
        imported: true,
      },
      busy: false,
      error: undefined,
      notice: undefined,
      readPdf: vi.fn(),
      acceptParsed: vi.fn(),
      clear: vi.fn(),
      setError: vi.fn(),
    } satisfies ResumeIngestionState);
    vi.mocked(putCandidateWorkspace).mockResolvedValue({} as never);
    vi.mocked(rebuildCandidateCampaignRoles).mockResolvedValue(undefined);
    vi.mocked(getCandidateCampaign).mockImplementation(async (signal) => {
      readCalls += 1;
      if (readCalls % 2 === 1) return staleCampaign;
      if (!signal) throw new Error('campaign poll signal missing');
      pollSignals.push(signal);
      return new Promise<CampaignMetaView>((_resolve, reject) => {
        signal.addEventListener('abort', () => reject(signal.reason), { once: true });
      });
    });
  });

  afterEach(() => {
    if (!wasUnmounted) act(() => root.unmount());
    vi.restoreAllMocks();
  });

  it('cancels the old poll on Back and starts one new poll when the campaign step is re-entered', async () => {
    await act(async () => {
      root.render(<OnboardingWizard hasAccount onComplete={() => undefined} />);
    });
    await advanceToCampaign(1);
    expect(pollSignals).toHaveLength(1);
    expect(vi.mocked(rebuildCandidateCampaignRoles)).toHaveBeenCalledTimes(1);

    await act(async () => clickButton('Назад'));
    expect(pollSignals[0].aborted).toBe(true);

    await advanceToCampaign(2);
    expect(pollSignals).toHaveLength(2);
    expect(pollSignals[1].aborted).toBe(false);
    expect(vi.mocked(rebuildCandidateCampaignRoles)).toHaveBeenCalledTimes(2);

    act(() => root.unmount());
    wasUnmounted = true;
    expect(pollSignals[1].aborted).toBe(true);
  });
});
