export interface CampaignReadiness {
  readonly roles: { readonly origin: string };
  readonly autoRoles?: readonly unknown[];
  readonly autoGeneratedAt?: string | null;
}

export type ModelCampaignResult<T> =
  | { readonly status: 'model'; readonly campaign: T }
  | { readonly status: 'timeout' };

export interface ModelCampaignWaitOptions {
  readonly timeoutMs?: number;
  readonly pollIntervalMs?: number;
  readonly now?: () => number;
  readonly sleep?: (milliseconds: number, signal?: AbortSignal) => Promise<void>;
  readonly signal?: AbortSignal;
  /** Время прошлого автонабора: принимается только набор, собранный после запроса пересборки. */
  readonly previousGeneratedAt?: string | null;
}

export interface ModelCampaignStart<T extends CampaignReadiness> {
  readonly persistProfile: (signal?: AbortSignal) => Promise<unknown>;
  readonly requestRebuild: (signal?: AbortSignal) => Promise<unknown>;
  readonly readCampaign: (signal?: AbortSignal) => Promise<T>;
  readonly waitOptions?: ModelCampaignWaitOptions;
  /** Called after POST /roles/rebuild succeeds, when the polling budget starts. */
  readonly onWaitStarted?: () => void;
}

export const DEFAULT_WAIT_MS = 90_000;
const DEFAULT_POLL_MS = 1_000;

/** Reads a fresh model campaign until it arrives or the bounded wait expires. */
export async function waitForModelCampaign<T extends CampaignReadiness>(
  readCampaign: (signal?: AbortSignal) => Promise<T>,
  options: ModelCampaignWaitOptions = {},
): Promise<ModelCampaignResult<T>> {
  const timeoutMs = options.timeoutMs ?? DEFAULT_WAIT_MS;
  const pollIntervalMs = options.pollIntervalMs ?? DEFAULT_POLL_MS;
  const now = options.now ?? Date.now;
  const sleep = options.sleep ?? delay;
  const signal = options.signal;
  const startedAt = now();

  while (true) {
    throwIfAborted(signal);
    try {
      const campaign = await readCampaign(signal);
      throwIfAborted(signal);
      if (isFreshModelSet(campaign, options.previousGeneratedAt ?? null)) {
        return { status: 'model', campaign };
      }
    } catch (error) {
      if (signal?.aborted) throw abortReason(signal);
      // A transient read failure is retried until the same bounded deadline.
      void error;
    }

    const remainingMs = timeoutMs - (now() - startedAt);
    if (remainingMs <= 0) return { status: 'timeout' };
    await sleep(Math.min(pollIntervalMs, remainingMs), signal);
  }
}

function isFreshModelSet(campaign: CampaignReadiness, previousGeneratedAt: string | null): boolean {
  const generatedAt = campaign.autoGeneratedAt ?? null;
  return (
    (campaign.autoRoles?.length ?? 0) > 0 &&
    generatedAt !== null &&
    generatedAt !== previousGeneratedAt
  );
}

export async function rebuildAndWaitForModelCampaign<T extends CampaignReadiness>(
  input: ModelCampaignStart<T>,
): Promise<ModelCampaignResult<T>> {
  const signal = input.waitOptions?.signal;
  throwIfAborted(signal);
  await input.persistProfile(signal);
  throwIfAborted(signal);
  const previousGeneratedAt = await input
    .readCampaign(signal)
    .then((campaign) => campaign.autoGeneratedAt ?? null)
    .catch(() => {
      if (signal?.aborted) throw abortReason(signal);
      return null;
    });
  throwIfAborted(signal);
  await input.requestRebuild(signal);
  throwIfAborted(signal);
  input.onWaitStarted?.();
  return waitForModelCampaign(input.readCampaign, {
    ...input.waitOptions,
    signal,
    previousGeneratedAt,
  });
}

function throwIfAborted(signal?: AbortSignal): void {
  if (signal?.aborted) throw abortReason(signal);
}

function abortReason(signal: AbortSignal): unknown {
  return signal.reason ?? new DOMException('Aborted', 'AbortError');
}

function delay(milliseconds: number, signal?: AbortSignal): Promise<void> {
  return new Promise((resolve, reject) => {
    if (signal?.aborted) {
      reject(abortReason(signal));
      return;
    }
    const finish = () => {
      signal?.removeEventListener('abort', abort);
      resolve();
    };
    const timer = setTimeout(finish, milliseconds);
    const abort = () => {
      clearTimeout(timer);
      signal?.removeEventListener('abort', abort);
      reject(abortReason(signal!));
    };
    signal?.addEventListener('abort', abort, { once: true });
  });
}
