import { describe, expect, it, vi } from 'vitest';
import { rebuildAndWaitForModelCampaign, waitForModelCampaign } from './onboardingCampaign';

function campaign(origin: string, autoGeneratedAt: string | null = '2026-09-27T10:00:00.000Z') {
  return {
    roles: { origin },
    autoRoles: origin === 'model' ? [{ id: 'ops.vp' }] : [],
    autoGeneratedAt: origin === 'model' ? autoGeneratedAt : null,
  };
}

describe('waitForModelCampaign', () => {
  it('waits for a model role set and returns the campaign that is ready', async () => {
    const read = vi
      .fn()
      .mockResolvedValueOnce(campaign('profile'))
      .mockResolvedValueOnce(campaign('model'));
    const result = await waitForModelCampaign(read, {
      timeoutMs: 90,
      pollIntervalMs: 10,
      sleep: async () => undefined,
    });

    expect(result).toEqual({ status: 'model', campaign: campaign('model') });
    expect(read).toHaveBeenCalledTimes(2);
  });

  it('keeps polling through temporary read failures', async () => {
    const read = vi
      .fn()
      .mockRejectedValueOnce(new Error('temporary'))
      .mockResolvedValueOnce(campaign('model'));
    const result = await waitForModelCampaign(read, {
      timeoutMs: 90,
      pollIntervalMs: 10,
      sleep: async () => undefined,
    });

    expect(result.status).toBe('model');
    expect(read).toHaveBeenCalledTimes(2);
  });

  it('returns an explicit timeout after the wait limit', async () => {
    let currentTime = 0;
    const read = vi.fn().mockResolvedValue(campaign('profile'));
    const result = await waitForModelCampaign(read, {
      timeoutMs: 90,
      pollIntervalMs: 30,
      now: () => currentTime,
      sleep: async (milliseconds) => {
        currentTime += milliseconds;
      },
    });

    expect(result).toEqual({ status: 'timeout' });
    expect(currentTime).toBe(90);
    expect(read).toHaveBeenCalledTimes(4);
  });

  it('ignores the role set built before the rebuild request', async () => {
    const stale = campaign('model', '2026-09-26T09:00:00.000Z');
    const fresh = campaign('model', '2026-09-27T10:00:00.000Z');
    const read = vi
      .fn()
      .mockResolvedValueOnce(stale)
      .mockResolvedValueOnce(stale)
      .mockResolvedValueOnce(fresh);
    const result = await rebuildAndWaitForModelCampaign({
      persistProfile: async () => undefined,
      requestRebuild: async () => undefined,
      readCampaign: read,
      waitOptions: { timeoutMs: 90, pollIntervalMs: 10, sleep: async () => undefined },
    });

    expect(result).toEqual({ status: 'model', campaign: fresh });
    expect(read).toHaveBeenCalledTimes(3);
  });

  it('accepts a fresh role set for a candidate whose campaign is explicit', async () => {
    const explicit = { ...campaign('model'), roles: { origin: 'explicit' } };
    const result = await waitForModelCampaign(vi.fn().mockResolvedValue(explicit), {
      timeoutMs: 90,
      pollIntervalMs: 10,
      sleep: async () => undefined,
      previousGeneratedAt: null,
    });

    expect(result.status).toBe('model');
  });
});
