import type { MeasuredAtsBoard } from './atsBoardSources';

/**
 * Что живая проба нашла у компаний из списков владельца (B199) 2026-09-05 с
 * маршрута eu-prod: `scripts/discover_ats_boards.py` — одна попытка на
 * провайдера, слаг взят из домена карьерной страницы и из имени компании.
 *
 * Каждая доска здесь **подтверждена принадлежностью**: либо сама лента
 * называет работодателя тем же именем, либо имя компании встречается в тексте
 * её же вакансий (`scripts/verify_ats_boards.py`). Проверка не декоративная:
 * она отсеяла 15 совпадений по слагу, где `career`, `job`, `us`, `meta` и `aha`
 * оказались досками совсем других компаний. Полный отчёт с отказами —
 * `docs/v1-release/tasks/evidence/B202-ats-boards/`.
 */
export const MEASURED_ATS_BOARDS: readonly MeasuredAtsBoard[] = [
  {
    company: '1Password',
    provider: 'ashby',
    board: '1password',
    jobs: 62,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Airbyte',
    provider: 'ashby',
    board: 'airbyte',
    jobs: 13,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'AirGarage',
    provider: 'ashby',
    board: 'airgarage',
    jobs: 5,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Airwallex',
    provider: 'ashby',
    board: 'airwallex',
    jobs: 585,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Alan',
    provider: 'ashby',
    board: 'alan',
    jobs: 111,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Andela',
    provider: 'ashby',
    board: 'andela',
    jobs: 17,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Ashby',
    provider: 'ashby',
    board: 'ashby',
    jobs: 72,
    observedAt: '2026-09-05',
    lists: ['drive'],
  },
  {
    company: 'Astronomer',
    provider: 'ashby',
    board: 'astronomer',
    jobs: 21,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Back Market',
    provider: 'ashby',
    board: 'backmarket',
    jobs: 19,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Beamery',
    provider: 'ashby',
    board: 'beamery',
    jobs: 7,
    observedAt: '2026-09-05',
    lists: ['buildin'],
  },
  {
    company: 'BetterUp',
    provider: 'ashby',
    board: 'betterup',
    jobs: 10,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Buffer',
    provider: 'ashby',
    board: 'buffer',
    jobs: 3,
    observedAt: '2026-09-05',
    lists: ['drive', 'telegraph'],
  },
  {
    company: 'Calibre',
    provider: 'ashby',
    board: 'calibre',
    jobs: 1,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Camunda',
    provider: 'ashby',
    board: 'camunda',
    jobs: 32,
    observedAt: '2026-09-05',
    lists: ['drive'],
  },
  {
    company: 'Capchase',
    provider: 'ashby',
    board: 'capchase',
    jobs: 6,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'CareMessage',
    provider: 'ashby',
    board: 'caremessage',
    jobs: 5,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Checkly',
    provider: 'ashby',
    board: 'checkly',
    jobs: 4,
    observedAt: '2026-09-05',
    lists: ['drive', 'telegraph'],
  },
  {
    company: 'ClickHouse',
    provider: 'ashby',
    board: 'clickhouse',
    jobs: 178,
    observedAt: '2026-09-05',
    lists: ['notion', 'drive'],
  },
  {
    company: 'ClickUp',
    provider: 'ashby',
    board: 'clickup',
    jobs: 62,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Close',
    provider: 'ashby',
    board: 'close',
    jobs: 8,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Deliveroo',
    provider: 'ashby',
    board: 'deliveroo',
    jobs: 209,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Docker',
    provider: 'ashby',
    board: 'docker',
    jobs: 62,
    observedAt: '2026-09-05',
    lists: ['drive', 'telegraph'],
  },
  {
    company: 'Docplanner',
    provider: 'ashby',
    board: 'docplanner',
    jobs: 30,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Doctolib',
    provider: 'ashby',
    board: 'doctolib',
    jobs: 126,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'ElevenLabs',
    provider: 'ashby',
    board: 'elevenlabs',
    jobs: 252,
    observedAt: '2026-09-05',
    lists: ['drive'],
  },
  {
    company: 'Envoy',
    provider: 'ashby',
    board: 'envoy',
    jobs: 18,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Flipper',
    provider: 'ashby',
    board: 'flipper',
    jobs: 8,
    observedAt: '2026-09-05',
    lists: ['buildin'],
  },
  {
    company: 'Haus',
    provider: 'ashby',
    board: 'haus',
    jobs: 13,
    observedAt: '2026-09-05',
    lists: ['drive'],
  },
  {
    company: 'Ledger',
    provider: 'ashby',
    board: 'ledger',
    jobs: 8,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Levelpath',
    provider: 'ashby',
    board: 'levelpath',
    jobs: 22,
    observedAt: '2026-09-05',
    lists: ['drive'],
  },
  {
    company: 'Lightspeed',
    provider: 'ashby',
    board: 'lightspeed',
    jobs: 4,
    observedAt: '2026-09-05',
    lists: ['buildin'],
  },
  {
    company: 'Lightspeed',
    provider: 'ashby',
    board: 'lightspeedhq',
    jobs: 161,
    observedAt: '2026-09-05',
    lists: ['buildin'],
  },
  {
    company: 'Miro',
    provider: 'ashby',
    board: 'miro',
    jobs: 38,
    observedAt: '2026-09-05',
    lists: ['notion', 'buildin', 'drive'],
  },
  {
    company: 'Mollie',
    provider: 'ashby',
    board: 'mollie',
    jobs: 45,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'n8n',
    provider: 'ashby',
    board: 'n8n',
    jobs: 41,
    observedAt: '2026-09-05',
    lists: ['drive'],
  },
  {
    company: 'Neon',
    provider: 'ashby',
    board: 'neon',
    jobs: 6,
    observedAt: '2026-09-05',
    lists: ['buildin'],
  },
  {
    company: 'Nous Research',
    provider: 'ashby',
    board: 'nousresearch',
    jobs: 10,
    observedAt: '2026-09-05',
    lists: ['drive'],
  },
  {
    company: 'Nylas',
    provider: 'ashby',
    board: 'nylas',
    jobs: 7,
    observedAt: '2026-09-05',
    lists: ['buildin'],
  },
  {
    company: 'Outschool',
    provider: 'ashby',
    board: 'outschool',
    jobs: 4,
    observedAt: '2026-09-05',
    lists: ['buildin'],
  },
  {
    company: 'Pleo',
    provider: 'ashby',
    board: 'pleo',
    jobs: 31,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'PostHog',
    provider: 'ashby',
    board: 'posthog',
    jobs: 9,
    observedAt: '2026-09-05',
    lists: ['drive'],
  },
  {
    company: 'ProductWind',
    provider: 'ashby',
    board: 'productwind',
    jobs: 2,
    observedAt: '2026-09-05',
    lists: ['drive'],
  },
  {
    company: 'Qonto',
    provider: 'ashby',
    board: 'qonto',
    jobs: 47,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Satispay',
    provider: 'ashby',
    board: 'satispay',
    jobs: 87,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Supercell',
    provider: 'ashby',
    board: 'supercell',
    jobs: 45,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Temporal',
    provider: 'ashby',
    board: 'temporal',
    jobs: 66,
    observedAt: '2026-09-05',
    lists: ['drive'],
  },
  {
    company: 'Trustly',
    provider: 'ashby',
    board: 'trustly',
    jobs: 19,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'UiPath',
    provider: 'ashby',
    board: 'uipath',
    jobs: 118,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Wayve',
    provider: 'ashby',
    board: 'wayve',
    jobs: 163,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Wonderful',
    provider: 'ashby',
    board: 'wonderful',
    jobs: 149,
    observedAt: '2026-09-05',
    lists: ['drive'],
  },
  {
    company: 'Xero',
    provider: 'ashby',
    board: 'xero',
    jobs: 113,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'ABBYY',
    provider: 'greenhouse',
    board: 'abbyy',
    jobs: 11,
    observedAt: '2026-09-05',
    lists: ['buildin'],
  },
  {
    company: 'Acquia',
    provider: 'greenhouse',
    board: 'acquia',
    jobs: 11,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Adyen',
    provider: 'greenhouse',
    board: 'adyen',
    jobs: 231,
    observedAt: '2026-09-05',
    lists: ['notion', 'drive'],
  },
  {
    company: 'AE Studio',
    provider: 'greenhouse',
    board: 'aestudio',
    jobs: 6,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Affirm',
    provider: 'greenhouse',
    board: 'affirm',
    jobs: 205,
    observedAt: '2026-09-05',
    lists: ['buildin'],
  },
  {
    company: 'Algolia',
    provider: 'greenhouse',
    board: 'algolia',
    jobs: 30,
    observedAt: '2026-09-05',
    lists: ['drive'],
  },
  {
    company: 'AlphaSights',
    provider: 'greenhouse',
    board: 'alphasights',
    jobs: 81,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Appinio',
    provider: 'greenhouse',
    board: 'appinio',
    jobs: 7,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'ARK',
    provider: 'greenhouse',
    board: 'ark',
    jobs: 3,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Avride',
    provider: 'greenhouse',
    board: 'avride',
    jobs: 69,
    observedAt: '2026-09-05',
    lists: ['buildin'],
  },
  {
    company: 'Axios',
    provider: 'greenhouse',
    board: 'axios',
    jobs: 31,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Behavox',
    provider: 'greenhouse',
    board: 'behavox',
    jobs: 49,
    observedAt: '2026-09-05',
    lists: ['buildin'],
  },
  {
    company: 'Bitpanda',
    provider: 'greenhouse',
    board: 'bitpanda',
    jobs: 28,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Cabify',
    provider: 'greenhouse',
    board: 'cabify',
    jobs: 64,
    observedAt: '2026-09-05',
    lists: ['notion', 'telegraph'],
  },
  {
    company: 'Canonical',
    provider: 'greenhouse',
    board: 'canonical',
    jobs: 302,
    observedAt: '2026-09-05',
    lists: ['drive', 'telegraph'],
  },
  {
    company: 'Careem',
    provider: 'greenhouse',
    board: 'careem',
    jobs: 19,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Catawiki',
    provider: 'greenhouse',
    board: 'catawiki',
    jobs: 49,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Celonis',
    provider: 'greenhouse',
    board: 'celonis',
    jobs: 274,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'CircleCI',
    provider: 'greenhouse',
    board: 'circleci',
    jobs: 7,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Cloudflare',
    provider: 'greenhouse',
    board: 'cloudflare',
    jobs: 331,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Coinbase',
    provider: 'greenhouse',
    board: 'coinbase',
    jobs: 192,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Comet',
    provider: 'greenhouse',
    board: 'comet',
    jobs: 3,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'commercetools',
    provider: 'greenhouse',
    board: 'commercetools',
    jobs: 22,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Compass Pathways',
    provider: 'greenhouse',
    board: 'compasspathways',
    jobs: 117,
    observedAt: '2026-09-05',
    lists: ['buildin'],
  },
  {
    company: 'ConsenSys',
    provider: 'greenhouse',
    board: 'consensys',
    jobs: 7,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Coursera',
    provider: 'greenhouse',
    board: 'coursera',
    jobs: 22,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Customer.io',
    provider: 'greenhouse',
    board: 'customerio',
    jobs: 28,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Dashlane',
    provider: 'greenhouse',
    board: 'dashlane',
    jobs: 15,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Databricks',
    provider: 'greenhouse',
    board: 'databricks',
    jobs: 870,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'DataCamp',
    provider: 'greenhouse',
    board: 'datacamp',
    jobs: 32,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Datadog',
    provider: 'greenhouse',
    board: 'datadog',
    jobs: 441,
    observedAt: '2026-09-05',
    lists: ['notion', 'telegraph'],
  },
  {
    company: 'DBeaver',
    provider: 'greenhouse',
    board: 'dbeaver',
    jobs: 8,
    observedAt: '2026-09-05',
    lists: ['buildin'],
  },
  {
    company: 'Discord',
    provider: 'greenhouse',
    board: 'discord',
    jobs: 48,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Doctolib',
    provider: 'greenhouse',
    board: 'doctolib',
    jobs: 129,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Dropbox',
    provider: 'greenhouse',
    board: 'dropbox',
    jobs: 42,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Elastic',
    provider: 'greenhouse',
    board: 'elastic',
    jobs: 365,
    observedAt: '2026-09-05',
    lists: ['notion', 'telegraph'],
  },
  {
    company: 'Epic Games',
    provider: 'greenhouse',
    board: 'epicgames',
    jobs: 164,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Fastly',
    provider: 'greenhouse',
    board: 'fastly',
    jobs: 48,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Feedzai',
    provider: 'greenhouse',
    board: 'feedzai',
    jobs: 35,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Flo Health',
    provider: 'greenhouse',
    board: 'flohealth',
    jobs: 29,
    observedAt: '2026-09-05',
    lists: ['buildin', 'drive'],
  },
  {
    company: 'Flow Traders',
    provider: 'greenhouse',
    board: 'flowtraders',
    jobs: 43,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Gensyn',
    provider: 'greenhouse',
    board: 'gensyn',
    jobs: 3,
    observedAt: '2026-09-05',
    lists: ['drive'],
  },
  {
    company: 'GetYourGuide',
    provider: 'greenhouse',
    board: 'getyourguide',
    jobs: 56,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Gitlab',
    provider: 'greenhouse',
    board: 'gitlab',
    jobs: 229,
    observedAt: '2026-09-05',
    lists: ['buildin', 'drive'],
  },
  {
    company: 'HelloFresh',
    provider: 'greenhouse',
    board: 'hellofresh',
    jobs: 451,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Innovecs',
    provider: 'greenhouse',
    board: 'innovecs',
    jobs: 13,
    observedAt: '2026-09-05',
    lists: ['drive'],
  },
  {
    company: 'JetBrains',
    provider: 'greenhouse',
    board: 'jetbrains',
    jobs: 72,
    observedAt: '2026-09-05',
    lists: ['notion', 'buildin', 'drive'],
  },
  {
    company: 'Lokalise',
    provider: 'greenhouse',
    board: 'lokalise',
    jobs: 7,
    observedAt: '2026-09-05',
    lists: ['buildin', 'drive'],
  },
  {
    company: 'Mercari',
    provider: 'greenhouse',
    board: 'mercari',
    jobs: 2,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Monzo',
    provider: 'greenhouse',
    board: 'monzo',
    jobs: 66,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'N26',
    provider: 'greenhouse',
    board: 'n26',
    jobs: 62,
    observedAt: '2026-09-05',
    lists: ['notion', 'drive'],
  },
  {
    company: 'Nebius',
    provider: 'greenhouse',
    board: 'nebius',
    jobs: 375,
    observedAt: '2026-09-05',
    lists: ['buildin'],
  },
  {
    company: 'Nordeus',
    provider: 'greenhouse',
    board: 'nordeus',
    jobs: 10,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Nova Credit',
    provider: 'greenhouse',
    board: 'novacredit',
    jobs: 11,
    observedAt: '2026-09-05',
    lists: ['buildin'],
  },
  {
    company: 'Outschool',
    provider: 'greenhouse',
    board: 'outschool',
    jobs: 4,
    observedAt: '2026-09-05',
    lists: ['buildin'],
  },
  {
    company: 'OUTSIDE DIGITAL (ex Kodix)',
    provider: 'greenhouse',
    board: 'outside',
    jobs: 17,
    observedAt: '2026-09-05',
    lists: ['buildin'],
  },
  {
    company: 'PandaDoc',
    provider: 'greenhouse',
    board: 'pandadoc',
    jobs: 25,
    observedAt: '2026-09-05',
    lists: ['buildin', 'drive'],
  },
  {
    company: 'Payoneer',
    provider: 'greenhouse',
    board: 'payoneer',
    jobs: 124,
    observedAt: '2026-09-05',
    lists: ['drive'],
  },
  {
    company: 'PayPay',
    provider: 'greenhouse',
    board: 'paypay',
    jobs: 86,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Picsart',
    provider: 'greenhouse',
    board: 'picsart',
    jobs: 9,
    observedAt: '2026-09-05',
    lists: ['buildin'],
  },
  {
    company: 'Plata Card',
    provider: 'greenhouse',
    board: 'platacard',
    jobs: 171,
    observedAt: '2026-09-05',
    lists: ['drive'],
  },
  {
    company: 'Postman',
    provider: 'greenhouse',
    board: 'postman',
    jobs: 63,
    observedAt: '2026-09-05',
    lists: ['drive'],
  },
  {
    company: 'Proton',
    provider: 'greenhouse',
    board: 'proton',
    jobs: 72,
    observedAt: '2026-09-05',
    lists: ['notion', 'drive'],
  },
  {
    company: 'Scandit',
    provider: 'greenhouse',
    board: 'scandit',
    jobs: 10,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Sila Nanotechnologies',
    provider: 'greenhouse',
    board: 'silananotechnologies',
    jobs: 30,
    observedAt: '2026-09-05',
    lists: ['buildin'],
  },
  {
    company: 'Skyscanner',
    provider: 'greenhouse',
    board: 'skyscanner',
    jobs: 3,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Soft2Bet',
    provider: 'greenhouse',
    board: 'soft2bet',
    jobs: 8,
    observedAt: '2026-09-05',
    lists: ['buildin'],
  },
  {
    company: 'Spryker',
    provider: 'greenhouse',
    board: 'spryker',
    jobs: 2,
    observedAt: '2026-09-05',
    lists: ['buildin'],
  },
  {
    company: 'Stripe',
    provider: 'greenhouse',
    board: 'stripe',
    jobs: 615,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'SumUp',
    provider: 'greenhouse',
    board: 'sumup',
    jobs: 409,
    observedAt: '2026-09-05',
    lists: ['notion', 'drive'],
  },
  {
    company: 'Tamara',
    provider: 'greenhouse',
    board: 'tamara',
    jobs: 33,
    observedAt: '2026-09-05',
    lists: ['drive'],
  },
  {
    company: 'Toloka',
    provider: 'greenhouse',
    board: 'toloka',
    jobs: 18,
    observedAt: '2026-09-05',
    lists: ['buildin'],
  },
  {
    company: 'Trade Republic',
    provider: 'greenhouse',
    board: 'traderepublic',
    jobs: 1,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Truecaller',
    provider: 'greenhouse',
    board: 'truecaller',
    jobs: 32,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Trustpilot',
    provider: 'greenhouse',
    board: 'trustpilot',
    jobs: 48,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Typeform',
    provider: 'greenhouse',
    board: 'typeform',
    jobs: 11,
    observedAt: '2026-09-05',
    lists: ['notion', 'drive'],
  },
  {
    company: 'Veriff',
    provider: 'greenhouse',
    board: 'veriff',
    jobs: 10,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Wayve',
    provider: 'greenhouse',
    board: 'wayve',
    jobs: 166,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Webflow',
    provider: 'greenhouse',
    board: 'webflow',
    jobs: 29,
    observedAt: '2026-09-05',
    lists: ['buildin'],
  },
  {
    company: 'Wise',
    provider: 'greenhouse',
    board: 'wise',
    jobs: 22,
    observedAt: '2026-09-05',
    lists: ['notion', 'drive'],
  },
  {
    company: 'Wolt',
    provider: 'greenhouse',
    board: 'wolt',
    jobs: 242,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'WPP plc',
    provider: 'greenhouse',
    board: 'wpp',
    jobs: 211,
    observedAt: '2026-09-05',
    lists: ['drive'],
  },
  {
    company: 'Wrike',
    provider: 'greenhouse',
    board: 'wrike',
    jobs: 70,
    observedAt: '2026-09-05',
    lists: ['buildin', 'drive'],
  },
  {
    company: 'Zscaler',
    provider: 'greenhouse',
    board: 'zscaler',
    jobs: 361,
    observedAt: '2026-09-05',
    lists: ['drive'],
  },
  {
    company: 'ActiveCampaign',
    provider: 'lever',
    board: 'activecampaign',
    jobs: 12,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Aerostrat',
    provider: 'lever',
    board: 'aerostrat',
    jobs: 3,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'airSlate',
    provider: 'lever',
    board: 'airslate',
    jobs: 13,
    observedAt: '2026-09-05',
    lists: ['buildin'],
  },
  {
    company: 'Anomali',
    provider: 'lever',
    board: 'anomali',
    jobs: 10,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'AppFollow',
    provider: 'lever',
    board: 'appfollow',
    jobs: 2,
    observedAt: '2026-09-05',
    lists: ['buildin'],
  },
  {
    company: 'BlueCat Networks',
    provider: 'lever',
    board: 'bluecatnetworks',
    jobs: 21,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Bounteous',
    provider: 'lever',
    board: 'bounteous',
    jobs: 28,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Brevo (Sendinblue)',
    provider: 'lever',
    board: 'brevo',
    jobs: 17,
    observedAt: '2026-09-05',
    lists: ['drive'],
  },
  {
    company: 'BriteCore',
    provider: 'lever',
    board: 'britecore',
    jobs: 8,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'charity: water',
    provider: 'lever',
    board: 'charitywater',
    jobs: 4,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Collabora',
    provider: 'lever',
    board: 'collabora',
    jobs: 3,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Contentsquare',
    provider: 'lever',
    board: 'contentsquare',
    jobs: 29,
    observedAt: '2026-09-05',
    lists: ['notion', 'drive'],
  },
  {
    company: 'DroneDeploy',
    provider: 'lever',
    board: 'dronedeploy',
    jobs: 9,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Easybrain',
    provider: 'lever',
    board: 'easybrain',
    jobs: 10,
    observedAt: '2026-09-05',
    lists: ['buildin'],
  },
  {
    company: 'GoPuff',
    provider: 'lever',
    board: 'gopuff',
    jobs: 765,
    observedAt: '2026-09-05',
    lists: ['buildin'],
  },
  {
    company: 'Ledger',
    provider: 'lever',
    board: 'ledger',
    jobs: 1,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Neon',
    provider: 'lever',
    board: 'neon',
    jobs: 12,
    observedAt: '2026-09-05',
    lists: ['buildin'],
  },
  {
    company: 'Pipedrive',
    provider: 'lever',
    board: 'pipedrive',
    jobs: 16,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Planner 5D',
    provider: 'lever',
    board: 'planner5d',
    jobs: 10,
    observedAt: '2026-09-05',
    lists: ['buildin'],
  },
  {
    company: 'Qonto',
    provider: 'lever',
    board: 'qonto',
    jobs: 47,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Spotify',
    provider: 'lever',
    board: 'spotify',
    jobs: 78,
    observedAt: '2026-09-05',
    lists: ['notion', 'drive'],
  },
  {
    company: 'Sword Health',
    provider: 'lever',
    board: 'swordhealth',
    jobs: 19,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Truv',
    provider: 'lever',
    board: 'truv',
    jobs: 12,
    observedAt: '2026-09-05',
    lists: ['buildin'],
  },
  {
    company: 'Xsolla',
    provider: 'lever',
    board: 'xsolla',
    jobs: 176,
    observedAt: '2026-09-05',
    lists: ['buildin', 'drive'],
  },
  {
    company: '11 bit studios',
    provider: 'recruitee',
    board: '11bitstudios',
    jobs: 5,
    observedAt: '2026-09-05',
    lists: ['notion'],
  },
  {
    company: 'Adzuna',
    provider: 'recruitee',
    board: 'adzuna',
    jobs: 1,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Aerolab',
    provider: 'recruitee',
    board: 'aerolab',
    jobs: 3,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  {
    company: 'Intento',
    provider: 'recruitee',
    board: 'intento',
    jobs: 1,
    observedAt: '2026-09-05',
    lists: ['buildin', 'drive'],
  },
  {
    company: 'Kodland',
    provider: 'recruitee',
    board: 'kodland',
    jobs: 60,
    observedAt: '2026-09-05',
    lists: ['buildin'],
  },
  {
    company: 'OLX',
    provider: 'recruitee',
    board: 'olx',
    jobs: 1,
    observedAt: '2026-09-05',
    lists: ['buildin'],
  },
  {
    company: 'Playrix',
    provider: 'recruitee',
    board: 'playrix',
    jobs: 3,
    observedAt: '2026-09-05',
    lists: ['notion', 'buildin', 'drive'],
  },
  {
    company: 'Admirals',
    provider: 'workable',
    board: 'admirals',
    jobs: 2,
    observedAt: '2026-09-05',
    lists: ['buildin'],
  },
  {
    company: 'Aha!',
    provider: 'workable',
    board: 'aha',
    jobs: 5,
    observedAt: '2026-09-05',
    lists: ['telegraph'],
  },
  // 2026-09-14 — крупные и популярные компании по списку владельца (B216):
  // `scripts/discover_ats_boards.py` + `scripts/verify_ats_boards.py` с прод-VM,
  // 392 компании → 214 досок → 203 подтверждены; четыре с ребрендом
  // (Cursor, Intercom/Fin, Gympass→Wellhub, Orca) приняты по совпадению бренда.
  {
    company: 'Alchemy',
    provider: 'ashby',
    board: 'alchemy',
    jobs: 20,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Anyscale',
    provider: 'ashby',
    board: 'anyscale',
    jobs: 20,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Baseten',
    provider: 'ashby',
    board: 'baseten',
    jobs: 94,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Benchling',
    provider: 'ashby',
    board: 'benchling',
    jobs: 51,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Bubble',
    provider: 'ashby',
    board: 'bubble',
    jobs: 8,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Cerebras',
    provider: 'ashby',
    board: 'cerebras',
    jobs: 111,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Character AI',
    provider: 'ashby',
    board: 'character',
    jobs: 13,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Cognition',
    provider: 'ashby',
    board: 'cognition',
    jobs: 94,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Cohere',
    provider: 'ashby',
    board: 'cohere',
    jobs: 145,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Confluent',
    provider: 'ashby',
    board: 'confluent',
    jobs: 21,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Crusoe',
    provider: 'ashby',
    board: 'crusoe',
    jobs: 369,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Cursor (Anysphere)',
    provider: 'ashby',
    board: 'cursor',
    jobs: 127,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Decagon',
    provider: 'ashby',
    board: 'decagon',
    jobs: 140,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Deepgram',
    provider: 'ashby',
    board: 'deepgram',
    jobs: 92,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Dovetail',
    provider: 'ashby',
    board: 'dovetail',
    jobs: 9,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Fireworks AI',
    provider: 'ashby',
    board: 'fireworks',
    jobs: 74,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'FullStory',
    provider: 'ashby',
    board: 'fullstory',
    jobs: 6,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Glide',
    provider: 'ashby',
    board: 'glide',
    jobs: 11,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Harvey',
    provider: 'ashby',
    board: 'harvey',
    jobs: 325,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Hex',
    provider: 'ashby',
    board: 'hex',
    jobs: 33,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'InfluxData',
    provider: 'ashby',
    board: 'influxdata',
    jobs: 3,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Lambda',
    provider: 'ashby',
    board: 'lambda',
    jobs: 89,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'LangChain',
    provider: 'ashby',
    board: 'langchain',
    jobs: 108,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Linear',
    provider: 'ashby',
    board: 'linear',
    jobs: 30,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'LlamaIndex',
    provider: 'ashby',
    board: 'llamaindex',
    jobs: 11,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Lovable',
    provider: 'ashby',
    board: 'lovable',
    jobs: 82,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Modal',
    provider: 'ashby',
    board: 'modal',
    jobs: 31,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Moon Active',
    provider: 'ashby',
    board: 'moonactive',
    jobs: 38,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Mural',
    provider: 'ashby',
    board: 'mural',
    jobs: 10,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'NerdWallet',
    provider: 'ashby',
    board: 'nerdwallet',
    jobs: 19,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Notion',
    provider: 'ashby',
    board: 'notion',
    jobs: 126,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Nubank',
    provider: 'ashby',
    board: 'nubank',
    jobs: 118,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'OpenAI',
    provider: 'ashby',
    board: 'openai',
    jobs: 794,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'OpenSea',
    provider: 'ashby',
    board: 'opensea',
    jobs: 2,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Orca Security',
    provider: 'ashby',
    board: 'orca',
    jobs: 1,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Percona',
    provider: 'ashby',
    board: 'percona',
    jobs: 17,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Perplexity',
    provider: 'ashby',
    board: 'perplexity',
    jobs: 115,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Pinecone',
    provider: 'ashby',
    board: 'pinecone',
    jobs: 7,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Plaid',
    provider: 'ashby',
    board: 'plaid',
    jobs: 111,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Poolside',
    provider: 'ashby',
    board: 'poolside',
    jobs: 13,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Ramp',
    provider: 'ashby',
    board: 'ramp',
    jobs: 145,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Redis',
    provider: 'ashby',
    board: 'redis',
    jobs: 20,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Render',
    provider: 'ashby',
    board: 'render',
    jobs: 36,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Replit',
    provider: 'ashby',
    board: 'replit',
    jobs: 76,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Sanity',
    provider: 'ashby',
    board: 'sanity',
    jobs: 31,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Sentry',
    provider: 'ashby',
    board: 'sentry',
    jobs: 43,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Sierra',
    provider: 'ashby',
    board: 'sierra',
    jobs: 210,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Snowflake',
    provider: 'ashby',
    board: 'snowflake',
    jobs: 368,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Sprig',
    provider: 'ashby',
    board: 'sprig',
    jobs: 6,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Supabase',
    provider: 'ashby',
    board: 'supabase',
    jobs: 60,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Synthesia',
    provider: 'ashby',
    board: 'synthesia',
    jobs: 56,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'tldraw',
    provider: 'ashby',
    board: 'tldraw',
    jobs: 3,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Chroma',
    provider: 'ashby',
    board: 'trychroma',
    jobs: 1,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Uniswap',
    provider: 'ashby',
    board: 'uniswap',
    jobs: 9,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Unstructured',
    provider: 'ashby',
    board: 'unstructured',
    jobs: 5,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Vanta',
    provider: 'ashby',
    board: 'vanta',
    jobs: 105,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Weaviate',
    provider: 'ashby',
    board: 'weaviate',
    jobs: 2,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Zapier',
    provider: 'ashby',
    board: 'zapier',
    jobs: 6,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Airbnb',
    provider: 'greenhouse',
    board: 'airbnb',
    jobs: 164,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Airtable',
    provider: 'greenhouse',
    board: 'airtable',
    jobs: 16,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Amplitude',
    provider: 'greenhouse',
    board: 'amplitude',
    jobs: 38,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Anthropic',
    provider: 'greenhouse',
    board: 'anthropic',
    jobs: 596,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'AppsFlyer',
    provider: 'greenhouse',
    board: 'appsflyer',
    jobs: 47,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Asana',
    provider: 'greenhouse',
    board: 'asana',
    jobs: 103,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'AssemblyAI',
    provider: 'greenhouse',
    board: 'assemblyai',
    jobs: 18,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Attentive',
    provider: 'greenhouse',
    board: 'attentive',
    jobs: 34,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Bitso',
    provider: 'greenhouse',
    board: 'bitso',
    jobs: 6,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Block',
    provider: 'greenhouse',
    board: 'block',
    jobs: 207,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Blockchain.com',
    provider: 'greenhouse',
    board: 'blockchain',
    jobs: 43,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Braze',
    provider: 'greenhouse',
    board: 'braze',
    jobs: 280,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Brex',
    provider: 'greenhouse',
    board: 'brex',
    jobs: 272,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Calendly',
    provider: 'greenhouse',
    board: 'calendly',
    jobs: 11,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Carta',
    provider: 'greenhouse',
    board: 'carta',
    jobs: 64,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Cato Networks',
    provider: 'greenhouse',
    board: 'catonetworks',
    jobs: 104,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Checkr',
    provider: 'greenhouse',
    board: 'checkr',
    jobs: 49,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Chime',
    provider: 'greenhouse',
    board: 'chime',
    jobs: 70,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Cockroach Labs',
    provider: 'greenhouse',
    board: 'cockroachlabs',
    jobs: 21,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Contentful',
    provider: 'greenhouse',
    board: 'contentful',
    jobs: 6,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'CoreWeave',
    provider: 'greenhouse',
    board: 'coreweave',
    jobs: 295,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Domino',
    provider: 'greenhouse',
    board: 'dominodatalab',
    jobs: 22,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Dremio',
    provider: 'greenhouse',
    board: 'dremio',
    jobs: 6,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Duolingo',
    provider: 'greenhouse',
    board: 'duolingo',
    jobs: 80,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'EDB',
    provider: 'greenhouse',
    board: 'edb',
    jobs: 13,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Figma',
    provider: 'greenhouse',
    board: 'figma',
    jobs: 153,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Fireblocks',
    provider: 'greenhouse',
    board: 'fireblocks',
    jobs: 75,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Fivetran',
    provider: 'greenhouse',
    board: 'fivetran',
    jobs: 197,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Flexport',
    provider: 'greenhouse',
    board: 'flexport',
    jobs: 179,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Forter',
    provider: 'greenhouse',
    board: 'forter',
    jobs: 32,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Glide',
    provider: 'greenhouse',
    board: 'glide',
    jobs: 1,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Grafana Labs',
    provider: 'greenhouse',
    board: 'grafanalabs',
    jobs: 116,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Gusto',
    provider: 'greenhouse',
    board: 'gusto',
    jobs: 95,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Wellhub',
    provider: 'greenhouse',
    board: 'gympass',
    jobs: 94,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Instacart',
    provider: 'greenhouse',
    board: 'instacart',
    jobs: 104,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Intercom',
    provider: 'greenhouse',
    board: 'intercom',
    jobs: 121,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'JFrog',
    provider: 'greenhouse',
    board: 'jfrog',
    jobs: 60,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Klaviyo',
    provider: 'greenhouse',
    board: 'klaviyo',
    jobs: 137,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Labelbox',
    provider: 'greenhouse',
    board: 'labelbox',
    jobs: 10,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Lattice',
    provider: 'greenhouse',
    board: 'lattice',
    jobs: 8,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'LaunchDarkly',
    provider: 'greenhouse',
    board: 'launchdarkly',
    jobs: 54,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Lightricks',
    provider: 'greenhouse',
    board: 'lightricks',
    jobs: 1,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Lovable',
    provider: 'greenhouse',
    board: 'lovable',
    jobs: 61,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Lyft',
    provider: 'greenhouse',
    board: 'lyft',
    jobs: 183,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Melio',
    provider: 'greenhouse',
    board: 'melio',
    jobs: 23,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Mercury',
    provider: 'greenhouse',
    board: 'mercury',
    jobs: 61,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Mixpanel',
    provider: 'greenhouse',
    board: 'mixpanel',
    jobs: 84,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'MongoDB',
    provider: 'greenhouse',
    board: 'mongodb',
    jobs: 405,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Mozilla',
    provider: 'greenhouse',
    board: 'mozilla',
    jobs: 60,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Netlify',
    provider: 'greenhouse',
    board: 'netlify',
    jobs: 1,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Nintendo',
    provider: 'greenhouse',
    board: 'nintendo',
    jobs: 50,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Okta',
    provider: 'greenhouse',
    board: 'okta',
    jobs: 324,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Orca Security',
    provider: 'greenhouse',
    board: 'orca',
    jobs: 2,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Orca Security',
    provider: 'greenhouse',
    board: 'orcasecurity',
    jobs: 9,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'PagerDuty',
    provider: 'greenhouse',
    board: 'pagerduty',
    jobs: 48,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Peloton',
    provider: 'greenhouse',
    board: 'peloton',
    jobs: 53,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Pendo',
    provider: 'greenhouse',
    board: 'pendo',
    jobs: 21,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Pinterest',
    provider: 'greenhouse',
    board: 'pinterest',
    jobs: 183,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'PlanetScale',
    provider: 'greenhouse',
    board: 'planetscale',
    jobs: 13,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'QuintoAndar',
    provider: 'greenhouse',
    board: 'quintoandar',
    jobs: 88,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Reddit',
    provider: 'greenhouse',
    board: 'reddit',
    jobs: 148,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Remote',
    provider: 'greenhouse',
    board: 'remote',
    jobs: 2,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Riot Games',
    provider: 'greenhouse',
    board: 'riotgames',
    jobs: 151,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Ripple',
    provider: 'greenhouse',
    board: 'ripple',
    jobs: 124,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Riskified',
    provider: 'greenhouse',
    board: 'riskified',
    jobs: 25,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Robinhood',
    provider: 'greenhouse',
    board: 'robinhood',
    jobs: 126,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Roblox',
    provider: 'greenhouse',
    board: 'roblox',
    jobs: 232,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Samsara',
    provider: 'greenhouse',
    board: 'samsara',
    jobs: 245,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Scale AI',
    provider: 'greenhouse',
    board: 'scaleai',
    jobs: 223,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Sigma',
    provider: 'greenhouse',
    board: 'sigmacomputing',
    jobs: 64,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'SingleStore',
    provider: 'greenhouse',
    board: 'singlestore',
    jobs: 31,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Smartsheet',
    provider: 'greenhouse',
    board: 'smartsheet',
    jobs: 92,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'SoFi',
    provider: 'greenhouse',
    board: 'sofi',
    jobs: 59,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'SpaceX',
    provider: 'greenhouse',
    board: 'spacex',
    jobs: 2414,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Squarespace',
    provider: 'greenhouse',
    board: 'squarespace',
    jobs: 28,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Stability AI',
    provider: 'greenhouse',
    board: 'stabilityai',
    jobs: 7,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Bolt.new',
    provider: 'greenhouse',
    board: 'stackblitz',
    jobs: 10,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Starburst',
    provider: 'greenhouse',
    board: 'starburst',
    jobs: 21,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Stone',
    provider: 'greenhouse',
    board: 'stone',
    jobs: 413,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Storyblok',
    provider: 'greenhouse',
    board: 'storyblok',
    jobs: 18,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Taboola',
    provider: 'greenhouse',
    board: 'taboola',
    jobs: 84,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Tailscale',
    provider: 'greenhouse',
    board: 'tailscale',
    jobs: 55,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Thoughtworks',
    provider: 'greenhouse',
    board: 'thoughtworks',
    jobs: 35,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Together AI',
    provider: 'greenhouse',
    board: 'togetherai',
    jobs: 63,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Tripadvisor',
    provider: 'greenhouse',
    board: 'tripadvisor',
    jobs: 98,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Turing',
    provider: 'greenhouse',
    board: 'turing',
    jobs: 21,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Twilio',
    provider: 'greenhouse',
    board: 'twilio',
    jobs: 149,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Twitch',
    provider: 'greenhouse',
    board: 'twitch',
    jobs: 55,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Vercel',
    provider: 'greenhouse',
    board: 'vercel',
    jobs: 86,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Wikimedia',
    provider: 'greenhouse',
    board: 'wikimedia',
    jobs: 17,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'xAI',
    provider: 'greenhouse',
    board: 'xai',
    jobs: 254,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Yotpo',
    provider: 'greenhouse',
    board: 'yotpo',
    jobs: 16,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Yugabyte',
    provider: 'greenhouse',
    board: 'yugabyte',
    jobs: 13,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'ZoomInfo',
    provider: 'greenhouse',
    board: 'zoominfo',
    jobs: 109,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Binance',
    provider: 'lever',
    board: 'binance',
    jobs: 289,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Crypto.com',
    provider: 'lever',
    board: 'crypto',
    jobs: 62,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'dLocal',
    provider: 'lever',
    board: 'dlocal',
    jobs: 54,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Fly.io',
    provider: 'lever',
    board: 'fly',
    jobs: 1,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Glide',
    provider: 'lever',
    board: 'glide',
    jobs: 20,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Kavak',
    provider: 'lever',
    board: 'kavak',
    jobs: 10,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'LogRocket',
    provider: 'lever',
    board: 'logrocket',
    jobs: 6,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Outreach',
    provider: 'lever',
    board: 'outreach',
    jobs: 30,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Palantir',
    provider: 'lever',
    board: 'palantir',
    jobs: 311,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Toptal',
    provider: 'lever',
    board: 'toptal',
    jobs: 17,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'WalkMe',
    provider: 'lever',
    board: 'walkme',
    jobs: 30,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Accenture',
    provider: 'recruitee',
    board: 'accenture',
    jobs: 2,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Gong',
    provider: 'recruitee',
    board: 'gong',
    jobs: 5,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Google',
    provider: 'recruitee',
    board: 'google',
    jobs: 1,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Prisma',
    provider: 'recruitee',
    board: 'prisma',
    jobs: 58,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Samsung',
    provider: 'recruitee',
    board: 'samsung',
    jobs: 1,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Hugging Face',
    provider: 'workable',
    board: 'huggingface',
    jobs: 6,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Jasper',
    provider: 'workable',
    board: 'jasper',
    jobs: 1,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Bosch Group',
    provider: 'smartrecruiters',
    board: 'BoschGroup',
    jobs: 4811,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Visa',
    provider: 'smartrecruiters',
    board: 'visa',
    jobs: 1240,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
  {
    company: 'Joom',
    provider: 'breezy',
    board: 'joom-group',
    jobs: 24,
    observedAt: '2026-09-14',
    lists: ['buildin'],
  },
  {
    company: 'Pinpoint',
    provider: 'pinpoint',
    board: 'pinpoint',
    jobs: 15,
    observedAt: '2026-09-14',
    lists: ['owner-2026-09-14'],
  },
];
