import type { MeasuredAtsBoard } from './atsBoardSources';

/**
 * Что живая проба нашла у компаний из списков владельца (B199) 2026-09-05 с
 * маршрута eu-prod: `scripts/discover_ats_boards.py` — одна попытка на
 * провайдера, слаг взят из домена карьерной страницы и из имени компании.
 *
 * Каждая доска здесь **подтверждена принадлежностью**: либо сама лента
 * называет работодателя тем же именем, либо имя компании встречается в тексте
 * её же вакансий (`scripts/verify_ats_boards.py`). Проверка не декоративная:
 * она отсеяла 15 совпадений по слагу, где `career`, `job`, `us`, `meta` и `aha`
 * оказались досками совсем других компаний. Полный отчёт с отказами —
 * `docs/v1-release/tasks/evidence/B202-ats-boards/`.
 */
export const MEASURED_ATS_BOARDS: readonly MeasuredAtsBoard[] = [
  { company: '1Password', provider: 'ashby', board: '1password', jobs: 62, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Airbyte', provider: 'ashby', board: 'airbyte', jobs: 13, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'AirGarage', provider: 'ashby', board: 'airgarage', jobs: 5, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Airwallex', provider: 'ashby', board: 'airwallex', jobs: 585, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Alan', provider: 'ashby', board: 'alan', jobs: 111, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Andela', provider: 'ashby', board: 'andela', jobs: 17, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Ashby', provider: 'ashby', board: 'ashby', jobs: 72, observedAt: '2026-09-05', lists: ['drive'] },
  { company: 'Astronomer', provider: 'ashby', board: 'astronomer', jobs: 21, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Back Market', provider: 'ashby', board: 'backmarket', jobs: 19, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Beamery', provider: 'ashby', board: 'beamery', jobs: 7, observedAt: '2026-09-05', lists: ['buildin'] },
  { company: 'BetterUp', provider: 'ashby', board: 'betterup', jobs: 10, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Buffer', provider: 'ashby', board: 'buffer', jobs: 3, observedAt: '2026-09-05', lists: ['drive', 'telegraph'] },
  { company: 'Calibre', provider: 'ashby', board: 'calibre', jobs: 1, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Camunda', provider: 'ashby', board: 'camunda', jobs: 32, observedAt: '2026-09-05', lists: ['drive'] },
  { company: 'Capchase', provider: 'ashby', board: 'capchase', jobs: 6, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'CareMessage', provider: 'ashby', board: 'caremessage', jobs: 5, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Checkly', provider: 'ashby', board: 'checkly', jobs: 4, observedAt: '2026-09-05', lists: ['drive', 'telegraph'] },
  { company: 'ClickHouse', provider: 'ashby', board: 'clickhouse', jobs: 178, observedAt: '2026-09-05', lists: ['notion', 'drive'] },
  { company: 'ClickUp', provider: 'ashby', board: 'clickup', jobs: 62, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Close', provider: 'ashby', board: 'close', jobs: 8, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Deliveroo', provider: 'ashby', board: 'deliveroo', jobs: 209, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Docker', provider: 'ashby', board: 'docker', jobs: 62, observedAt: '2026-09-05', lists: ['drive', 'telegraph'] },
  { company: 'Docplanner', provider: 'ashby', board: 'docplanner', jobs: 30, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Doctolib', provider: 'ashby', board: 'doctolib', jobs: 126, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'ElevenLabs', provider: 'ashby', board: 'elevenlabs', jobs: 252, observedAt: '2026-09-05', lists: ['drive'] },
  { company: 'Envoy', provider: 'ashby', board: 'envoy', jobs: 18, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Flipper', provider: 'ashby', board: 'flipper', jobs: 8, observedAt: '2026-09-05', lists: ['buildin'] },
  { company: 'Haus', provider: 'ashby', board: 'haus', jobs: 13, observedAt: '2026-09-05', lists: ['drive'] },
  { company: 'Ledger', provider: 'ashby', board: 'ledger', jobs: 8, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Levelpath', provider: 'ashby', board: 'levelpath', jobs: 22, observedAt: '2026-09-05', lists: ['drive'] },
  { company: 'Lightspeed', provider: 'ashby', board: 'lightspeed', jobs: 4, observedAt: '2026-09-05', lists: ['buildin'] },
  { company: 'Lightspeed', provider: 'ashby', board: 'lightspeedhq', jobs: 161, observedAt: '2026-09-05', lists: ['buildin'] },
  { company: 'Miro', provider: 'ashby', board: 'miro', jobs: 38, observedAt: '2026-09-05', lists: ['notion', 'buildin', 'drive'] },
  { company: 'Mollie', provider: 'ashby', board: 'mollie', jobs: 45, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'n8n', provider: 'ashby', board: 'n8n', jobs: 41, observedAt: '2026-09-05', lists: ['drive'] },
  { company: 'Neon', provider: 'ashby', board: 'neon', jobs: 6, observedAt: '2026-09-05', lists: ['buildin'] },
  { company: 'Nous Research', provider: 'ashby', board: 'nousresearch', jobs: 10, observedAt: '2026-09-05', lists: ['drive'] },
  { company: 'Nylas', provider: 'ashby', board: 'nylas', jobs: 7, observedAt: '2026-09-05', lists: ['buildin'] },
  { company: 'Outschool', provider: 'ashby', board: 'outschool', jobs: 4, observedAt: '2026-09-05', lists: ['buildin'] },
  { company: 'Pleo', provider: 'ashby', board: 'pleo', jobs: 31, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'PostHog', provider: 'ashby', board: 'posthog', jobs: 9, observedAt: '2026-09-05', lists: ['drive'] },
  { company: 'ProductWind', provider: 'ashby', board: 'productwind', jobs: 2, observedAt: '2026-09-05', lists: ['drive'] },
  { company: 'Qonto', provider: 'ashby', board: 'qonto', jobs: 47, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Satispay', provider: 'ashby', board: 'satispay', jobs: 87, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Supercell', provider: 'ashby', board: 'supercell', jobs: 45, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Temporal', provider: 'ashby', board: 'temporal', jobs: 66, observedAt: '2026-09-05', lists: ['drive'] },
  { company: 'Trustly', provider: 'ashby', board: 'trustly', jobs: 19, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'UiPath', provider: 'ashby', board: 'uipath', jobs: 118, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Wayve', provider: 'ashby', board: 'wayve', jobs: 163, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Wonderful', provider: 'ashby', board: 'wonderful', jobs: 149, observedAt: '2026-09-05', lists: ['drive'] },
  { company: 'Xero', provider: 'ashby', board: 'xero', jobs: 113, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'ABBYY', provider: 'greenhouse', board: 'abbyy', jobs: 11, observedAt: '2026-09-05', lists: ['buildin'] },
  { company: 'Acquia', provider: 'greenhouse', board: 'acquia', jobs: 11, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Adyen', provider: 'greenhouse', board: 'adyen', jobs: 231, observedAt: '2026-09-05', lists: ['notion', 'drive'] },
  { company: 'AE Studio', provider: 'greenhouse', board: 'aestudio', jobs: 6, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Affirm', provider: 'greenhouse', board: 'affirm', jobs: 205, observedAt: '2026-09-05', lists: ['buildin'] },
  { company: 'Algolia', provider: 'greenhouse', board: 'algolia', jobs: 30, observedAt: '2026-09-05', lists: ['drive'] },
  { company: 'AlphaSights', provider: 'greenhouse', board: 'alphasights', jobs: 81, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Appinio', provider: 'greenhouse', board: 'appinio', jobs: 7, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'ARK', provider: 'greenhouse', board: 'ark', jobs: 3, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Avride', provider: 'greenhouse', board: 'avride', jobs: 69, observedAt: '2026-09-05', lists: ['buildin'] },
  { company: 'Axios', provider: 'greenhouse', board: 'axios', jobs: 31, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Behavox', provider: 'greenhouse', board: 'behavox', jobs: 49, observedAt: '2026-09-05', lists: ['buildin'] },
  { company: 'Bitpanda', provider: 'greenhouse', board: 'bitpanda', jobs: 28, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Cabify', provider: 'greenhouse', board: 'cabify', jobs: 64, observedAt: '2026-09-05', lists: ['notion', 'telegraph'] },
  { company: 'Canonical', provider: 'greenhouse', board: 'canonical', jobs: 302, observedAt: '2026-09-05', lists: ['drive', 'telegraph'] },
  { company: 'Careem', provider: 'greenhouse', board: 'careem', jobs: 19, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Catawiki', provider: 'greenhouse', board: 'catawiki', jobs: 49, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Celonis', provider: 'greenhouse', board: 'celonis', jobs: 274, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'CircleCI', provider: 'greenhouse', board: 'circleci', jobs: 7, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Cloudflare', provider: 'greenhouse', board: 'cloudflare', jobs: 331, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Coinbase', provider: 'greenhouse', board: 'coinbase', jobs: 192, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Comet', provider: 'greenhouse', board: 'comet', jobs: 3, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'commercetools', provider: 'greenhouse', board: 'commercetools', jobs: 22, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Compass Pathways', provider: 'greenhouse', board: 'compasspathways', jobs: 117, observedAt: '2026-09-05', lists: ['buildin'] },
  { company: 'ConsenSys', provider: 'greenhouse', board: 'consensys', jobs: 7, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Coursera', provider: 'greenhouse', board: 'coursera', jobs: 22, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Customer.io', provider: 'greenhouse', board: 'customerio', jobs: 28, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Dashlane', provider: 'greenhouse', board: 'dashlane', jobs: 15, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Databricks', provider: 'greenhouse', board: 'databricks', jobs: 870, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'DataCamp', provider: 'greenhouse', board: 'datacamp', jobs: 32, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Datadog', provider: 'greenhouse', board: 'datadog', jobs: 441, observedAt: '2026-09-05', lists: ['notion', 'telegraph'] },
  { company: 'DBeaver', provider: 'greenhouse', board: 'dbeaver', jobs: 8, observedAt: '2026-09-05', lists: ['buildin'] },
  { company: 'Discord', provider: 'greenhouse', board: 'discord', jobs: 48, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Doctolib', provider: 'greenhouse', board: 'doctolib', jobs: 129, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Dropbox', provider: 'greenhouse', board: 'dropbox', jobs: 42, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Elastic', provider: 'greenhouse', board: 'elastic', jobs: 365, observedAt: '2026-09-05', lists: ['notion', 'telegraph'] },
  { company: 'Epic Games', provider: 'greenhouse', board: 'epicgames', jobs: 164, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Fastly', provider: 'greenhouse', board: 'fastly', jobs: 48, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Feedzai', provider: 'greenhouse', board: 'feedzai', jobs: 35, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Flo Health', provider: 'greenhouse', board: 'flohealth', jobs: 29, observedAt: '2026-09-05', lists: ['buildin', 'drive'] },
  { company: 'Flow Traders', provider: 'greenhouse', board: 'flowtraders', jobs: 43, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Gensyn', provider: 'greenhouse', board: 'gensyn', jobs: 3, observedAt: '2026-09-05', lists: ['drive'] },
  { company: 'GetYourGuide', provider: 'greenhouse', board: 'getyourguide', jobs: 56, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Gitlab', provider: 'greenhouse', board: 'gitlab', jobs: 229, observedAt: '2026-09-05', lists: ['buildin', 'drive'] },
  { company: 'HelloFresh', provider: 'greenhouse', board: 'hellofresh', jobs: 451, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Innovecs', provider: 'greenhouse', board: 'innovecs', jobs: 13, observedAt: '2026-09-05', lists: ['drive'] },
  { company: 'JetBrains', provider: 'greenhouse', board: 'jetbrains', jobs: 72, observedAt: '2026-09-05', lists: ['notion', 'buildin', 'drive'] },
  { company: 'Lokalise', provider: 'greenhouse', board: 'lokalise', jobs: 7, observedAt: '2026-09-05', lists: ['buildin', 'drive'] },
  { company: 'Mercari', provider: 'greenhouse', board: 'mercari', jobs: 2, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Monzo', provider: 'greenhouse', board: 'monzo', jobs: 66, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'N26', provider: 'greenhouse', board: 'n26', jobs: 62, observedAt: '2026-09-05', lists: ['notion', 'drive'] },
  { company: 'Nebius', provider: 'greenhouse', board: 'nebius', jobs: 375, observedAt: '2026-09-05', lists: ['buildin'] },
  { company: 'Nordeus', provider: 'greenhouse', board: 'nordeus', jobs: 10, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Nova Credit', provider: 'greenhouse', board: 'novacredit', jobs: 11, observedAt: '2026-09-05', lists: ['buildin'] },
  { company: 'Outschool', provider: 'greenhouse', board: 'outschool', jobs: 4, observedAt: '2026-09-05', lists: ['buildin'] },
  { company: 'OUTSIDE DIGITAL (ex Kodix)', provider: 'greenhouse', board: 'outside', jobs: 17, observedAt: '2026-09-05', lists: ['buildin'] },
  { company: 'PandaDoc', provider: 'greenhouse', board: 'pandadoc', jobs: 25, observedAt: '2026-09-05', lists: ['buildin', 'drive'] },
  { company: 'Payoneer', provider: 'greenhouse', board: 'payoneer', jobs: 124, observedAt: '2026-09-05', lists: ['drive'] },
  { company: 'PayPay', provider: 'greenhouse', board: 'paypay', jobs: 86, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Picsart', provider: 'greenhouse', board: 'picsart', jobs: 9, observedAt: '2026-09-05', lists: ['buildin'] },
  { company: 'Plata Card', provider: 'greenhouse', board: 'platacard', jobs: 171, observedAt: '2026-09-05', lists: ['drive'] },
  { company: 'Postman', provider: 'greenhouse', board: 'postman', jobs: 63, observedAt: '2026-09-05', lists: ['drive'] },
  { company: 'Proton', provider: 'greenhouse', board: 'proton', jobs: 72, observedAt: '2026-09-05', lists: ['notion', 'drive'] },
  { company: 'Scandit', provider: 'greenhouse', board: 'scandit', jobs: 10, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Sila Nanotechnologies', provider: 'greenhouse', board: 'silananotechnologies', jobs: 30, observedAt: '2026-09-05', lists: ['buildin'] },
  { company: 'Skyscanner', provider: 'greenhouse', board: 'skyscanner', jobs: 3, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Soft2Bet', provider: 'greenhouse', board: 'soft2bet', jobs: 8, observedAt: '2026-09-05', lists: ['buildin'] },
  { company: 'Spryker', provider: 'greenhouse', board: 'spryker', jobs: 2, observedAt: '2026-09-05', lists: ['buildin'] },
  { company: 'Stripe', provider: 'greenhouse', board: 'stripe', jobs: 615, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'SumUp', provider: 'greenhouse', board: 'sumup', jobs: 409, observedAt: '2026-09-05', lists: ['notion', 'drive'] },
  { company: 'Tamara', provider: 'greenhouse', board: 'tamara', jobs: 33, observedAt: '2026-09-05', lists: ['drive'] },
  { company: 'Toloka', provider: 'greenhouse', board: 'toloka', jobs: 18, observedAt: '2026-09-05', lists: ['buildin'] },
  { company: 'Trade Republic', provider: 'greenhouse', board: 'traderepublic', jobs: 1, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Truecaller', provider: 'greenhouse', board: 'truecaller', jobs: 32, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Trustpilot', provider: 'greenhouse', board: 'trustpilot', jobs: 48, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Typeform', provider: 'greenhouse', board: 'typeform', jobs: 11, observedAt: '2026-09-05', lists: ['notion', 'drive'] },
  { company: 'Veriff', provider: 'greenhouse', board: 'veriff', jobs: 10, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Wayve', provider: 'greenhouse', board: 'wayve', jobs: 166, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Webflow', provider: 'greenhouse', board: 'webflow', jobs: 29, observedAt: '2026-09-05', lists: ['buildin'] },
  { company: 'Wise', provider: 'greenhouse', board: 'wise', jobs: 22, observedAt: '2026-09-05', lists: ['notion', 'drive'] },
  { company: 'Wolt', provider: 'greenhouse', board: 'wolt', jobs: 242, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'WPP plc', provider: 'greenhouse', board: 'wpp', jobs: 211, observedAt: '2026-09-05', lists: ['drive'] },
  { company: 'Wrike', provider: 'greenhouse', board: 'wrike', jobs: 70, observedAt: '2026-09-05', lists: ['buildin', 'drive'] },
  { company: 'Zscaler', provider: 'greenhouse', board: 'zscaler', jobs: 361, observedAt: '2026-09-05', lists: ['drive'] },
  { company: 'ActiveCampaign', provider: 'lever', board: 'activecampaign', jobs: 12, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Aerostrat', provider: 'lever', board: 'aerostrat', jobs: 3, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'airSlate', provider: 'lever', board: 'airslate', jobs: 13, observedAt: '2026-09-05', lists: ['buildin'] },
  { company: 'Anomali', provider: 'lever', board: 'anomali', jobs: 10, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'AppFollow', provider: 'lever', board: 'appfollow', jobs: 2, observedAt: '2026-09-05', lists: ['buildin'] },
  { company: 'BlueCat Networks', provider: 'lever', board: 'bluecatnetworks', jobs: 21, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Bounteous', provider: 'lever', board: 'bounteous', jobs: 28, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Brevo (Sendinblue)', provider: 'lever', board: 'brevo', jobs: 17, observedAt: '2026-09-05', lists: ['drive'] },
  { company: 'BriteCore', provider: 'lever', board: 'britecore', jobs: 8, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'charity: water', provider: 'lever', board: 'charitywater', jobs: 4, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Collabora', provider: 'lever', board: 'collabora', jobs: 3, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Contentsquare', provider: 'lever', board: 'contentsquare', jobs: 29, observedAt: '2026-09-05', lists: ['notion', 'drive'] },
  { company: 'DroneDeploy', provider: 'lever', board: 'dronedeploy', jobs: 9, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Easybrain', provider: 'lever', board: 'easybrain', jobs: 10, observedAt: '2026-09-05', lists: ['buildin'] },
  { company: 'GoPuff', provider: 'lever', board: 'gopuff', jobs: 765, observedAt: '2026-09-05', lists: ['buildin'] },
  { company: 'Ledger', provider: 'lever', board: 'ledger', jobs: 1, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Neon', provider: 'lever', board: 'neon', jobs: 12, observedAt: '2026-09-05', lists: ['buildin'] },
  { company: 'Pipedrive', provider: 'lever', board: 'pipedrive', jobs: 16, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Planner 5D', provider: 'lever', board: 'planner5d', jobs: 10, observedAt: '2026-09-05', lists: ['buildin'] },
  { company: 'Qonto', provider: 'lever', board: 'qonto', jobs: 47, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Spotify', provider: 'lever', board: 'spotify', jobs: 78, observedAt: '2026-09-05', lists: ['notion', 'drive'] },
  { company: 'Sword Health', provider: 'lever', board: 'swordhealth', jobs: 19, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Truv', provider: 'lever', board: 'truv', jobs: 12, observedAt: '2026-09-05', lists: ['buildin'] },
  { company: 'Xsolla', provider: 'lever', board: 'xsolla', jobs: 176, observedAt: '2026-09-05', lists: ['buildin', 'drive'] },
  { company: '11 bit studios', provider: 'recruitee', board: '11bitstudios', jobs: 5, observedAt: '2026-09-05', lists: ['notion'] },
  { company: 'Adzuna', provider: 'recruitee', board: 'adzuna', jobs: 1, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Aerolab', provider: 'recruitee', board: 'aerolab', jobs: 3, observedAt: '2026-09-05', lists: ['telegraph'] },
  { company: 'Intento', provider: 'recruitee', board: 'intento', jobs: 1, observedAt: '2026-09-05', lists: ['buildin', 'drive'] },
  { company: 'Kodland', provider: 'recruitee', board: 'kodland', jobs: 60, observedAt: '2026-09-05', lists: ['buildin'] },
  { company: 'OLX', provider: 'recruitee', board: 'olx', jobs: 1, observedAt: '2026-09-05', lists: ['buildin'] },
  { company: 'Playrix', provider: 'recruitee', board: 'playrix', jobs: 3, observedAt: '2026-09-05', lists: ['notion', 'buildin', 'drive'] },
  { company: 'Admirals', provider: 'workable', board: 'admirals', jobs: 2, observedAt: '2026-09-05', lists: ['buildin'] },
  { company: 'Aha!', provider: 'workable', board: 'aha', jobs: 5, observedAt: '2026-09-05', lists: ['telegraph'] },
];
