import type { UnifiedVacancy } from '../domain/unifiedVacancy';

export const CURATED_TELEGRAM_VACANCIES: Record<string, UnifiedVacancy[]> = {
  'src-tg-itjobs': [
    {
      id: 'tg-itjobs-14902',
      fingerprint: 'tg-itjobs-14902',
      title: 'Senior Node.js / TypeScript Developer',
      company: 'Fintech Startup (Cyprus / Remote)',
      location: 'Remote',
      isRemote: true,
      experienceLevel: 'Senior',
      employmentType: 'Full-time',
      salary: { from: 4500, to: 6000, currency: 'USD' },
      description: 'Ищем опытного Backend разработчика на Node.js и TypeScript в европейский финтех-стартап. Предстоит разрабатывать отказоустойчивые платежные шлюзы, интеграции с банковскими провайдерами и модуль расчета комиссий в реальном времени.',
      responsibilities: [
        'Разработка микросервисов на Node.js, NestJS и TypeScript',
        'Проектирование схемы баз данных в PostgreSQL и работа с транзакционными операциями',
        'Организация асинхронного обмена сообщениями через Apache Kafka',
        'Написание качественных модульных и интеграционных тестов (Jest / Supertest)',
        'Интеграция с платежными системами по стандарту PCI-DSS',
      ],
      qualifications: [
        'Опыт коммерческой разработки на Node.js / TypeScript от 4 лет',
        'Глубокое понимание event loop, асинхронных паттернов и профилирования Node.js',
        'Уверенное владение PostgreSQL (индексы, блокировки, транзакции)',
        'Опыт работы с Docker, Kubernetes и облаком AWS',
      ],
      niceToHave: [
        'Опыт работы в финтех или крипто-проектах',
        'Разговорный английский язык уровня B2+',
      ],
      benefits: [
        'Выплаты в USD/EUR на зарубежные или РФ счета',
        'Гибкий график и полная удаленка без тайм-трекеров',
        'Оплата коворкинга и компенсация покупки техники',
        'Опционы компании после испытательного срока',
      ],
      aboutCompany: 'Международная платежная платформа нового поколения, обрабатывающая транзакции в более чем 40 странах.',
      contactInfo: '@hr_fintech_lead',
      requiredSkills: ['Node.js', 'TypeScript', 'NestJS', 'PostgreSQL', 'Kafka', 'AWS', 'Docker'],
      url: 'https://t.me/it_jobs/14902',
      provenance: { sourceType: 'telegram', sourceId: 'src-tg-itjobs', sourceUrl: 'https://t.me/it_jobs/14902', channelName: 'it_jobs', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-17T14:10:00.000Z',
      status: 'active',
    },
    {
      id: 'tg-itjobs-14905',
      fingerprint: 'tg-itjobs-14905',
      title: 'Engineering Manager (Core Services)',
      company: 'E-commerce Platform',
      location: 'Москва / Remote',
      isRemote: true,
      experienceLevel: 'Executive',
      employmentType: 'Full-time',
      salary: { from: 380000, to: 480000, currency: 'RUR', gross: false },
      description: 'В быстрорастущий e-commerce сервис требуется Engineering Manager для управления кросс-функциональной командой из 12 бэкенд и фронтенд инженеров. Фокус на выстраивании прозрачных процессов разработки и снижении Time to Market.',
      responsibilities: [
        'Управление командой инженеров: найм, 1-on-1, мотивация, постановка OKR и индивидуальные планы развития (PDP)',
        'Внедрение инженерных стандартов, мониторинг DORA-метрик (Deployment Frequency, Lead Time, MTTR)',
        'Синхронизация бэклога с Product Owner и бизнес-заказчиками',
        'Устранение узких мест в релизном цикле и координация сложных межкомандных проектов',
      ],
      qualifications: [
        'Опыт работы Engineering Manager или Team Lead от 3 лет',
        'Сильный инженерный бэкграунд в разработке распределенных систем',
        'Практический опыт найма и масштабирования технических команд',
        'Отличные навыки фасилитации, разрешения конфликтов и коммуникации',
      ],
      niceToHave: [
        'Опыт трансформации монолита в микросервисную архитектуру',
      ],
      benefits: [
        'Удаленная работа из любой локации (РФ или СНГ)',
        'ДМС со стоматологией и страхованием жизни',
        'Квартальные бонусы по выполнению командных OKR',
      ],
      aboutCompany: 'Один из лидеров онлайн-ритейла с миллионной аудиторией покупателей.',
      contactInfo: '@em_talent_search',
      requiredSkills: ['Engineering Management', 'Leadership', 'Agile', 'System Architecture', 'Mentorship', 'DORA'],
      url: 'https://t.me/it_jobs/14905',
      provenance: { sourceType: 'telegram', sourceId: 'src-tg-itjobs', sourceUrl: 'https://t.me/it_jobs/14905', channelName: 'it_jobs', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-17T12:00:00.000Z',
      status: 'active',
    },
  ],
  'src-tg-tproger': [
    {
      id: 'tg-tproger-8841',
      fingerprint: 'tg-tproger-8841',
      title: 'Team Lead Fullstack (React + Go)',
      company: 'Т-Банк',
      location: 'Москва / Remote',
      isRemote: true,
      experienceLevel: 'Lead',
      employmentType: 'Full-time',
      salary: { from: 420000, to: 550000, currency: 'RUR', gross: false },
      description: 'Т-Банк ищет Team Lead Fullstack разработчика для руководства командой цифровых платежных интерфейсов. Вы будете совмещать 40% управленческих задач и 60% сложной архитектурной разработки высоконагруженных сервисов.',
      responsibilities: [
        'Руководство разработкой платежных веб-интерфейсов и шлюзов',
        'Проектирование масштабируемой архитектуры на React 18+ и Go',
        'Код-ревью, распределение задач в спринте, контроль технического долга',
        'Взаимодействие с командами безопасности, тестирования и продуктовой аналитики',
      ],
      qualifications: [
        'Опыт разработки на Go и React / TypeScript от 4.5 лет',
        'Опыт руководства командой разработчиков от 1.5 лет',
        'Знание современных СУБД (PostgreSQL, ClickHouse), брокеров Kafka',
        'Понимание микросервисной архитектуры и практик CI/CD',
      ],
      niceToHave: [
        'Опыт работы в финтех-секторе и знание стандартов безопасности транзакций',
      ],
      benefits: [
        'Удаленная работа или гибрид в современных хабах по всей РФ',
        'ДМС премиум-уровня с покрытием стоматологии и телемедицины',
        'Скидки на продукты банка и льготные кредитные программы',
        'Годовой бонус за результаты команды',
      ],
      aboutCompany: 'Т-Банк — передовой финансовый и технологический холдинг, обслуживающий более 40 млн клиентов.',
      contactInfo: '@tbank_leads_recruiter',
      requiredSkills: ['Go', 'React', 'TypeScript', 'Team Lead', 'Kafka', 'Highload', 'ClickHouse'],
      url: 'https://t.me/tproger_jobs/8841',
      provenance: { sourceType: 'telegram', sourceId: 'src-tg-tproger', sourceUrl: 'https://t.me/tproger_jobs/8841', channelName: 'tproger_jobs', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-17T11:00:00.000Z',
      status: 'active',
    },
  ],
  'src-tg-react': [
    {
      id: 'tg-react-5120',
      fingerprint: 'tg-react-5120',
      title: 'Senior Frontend Developer (React 19 / Next.js)',
      company: 'AdTech Global Agency',
      location: 'Remote',
      isRemote: true,
      experienceLevel: 'Senior',
      employmentType: 'Full-time',
      salary: { from: 300000, to: 400000, currency: 'RUR', gross: false },
      description: 'Разработка аналитических дэшбордов реального времени для управления масштабными рекламными кампаниями. Требуется сильная экспертиза в React 19, Server Components, оптимизации рендеринга и WebGL визуализациях графиков.',
      responsibilities: [
        'Разработка сложных интерфейсов с большим объемом интерактивных графиков и таблиц',
        'Оптимизация рендеринга миллионов строк данных (виртуализация, Web Workers)',
        'Построение дизайн-системы с поддержкой кастомных тем и локализации',
        'Интеграция со стриминговыми WebSocket API',
      ],
      qualifications: [
        'Опыт разработки на React и TypeScript от 4 лет',
        'Опыт работы с Next.js App Router, Zustand, React Query / SWR',
        'Понимание браузерных оптимизаций памяти и рендеринга (Canvas / WebGL / SVG)',
        'Опыт написания Unit и E2E тестов',
      ],
      niceToHave: [
        'Опыт работы с D3.js, Chart.js или Three.js',
      ],
      benefits: [
        'Полностью удаленная работа, гибкий рабочий день',
        'Компенсация профессионального обучения и курсов',
        'Предоставление рабочего ноутбука',
      ],
      aboutCompany: 'Международная платформа для автоматизации programmatic рекламы и аналитики.',
      contactInfo: '@adtech_frontend_hr',
      requiredSkills: ['React', 'Next.js', 'TypeScript', 'Performance', 'WebGL', 'Zustand', 'WebSockets'],
      url: 'https://t.me/job_react/5120',
      provenance: { sourceType: 'telegram', sourceId: 'src-tg-react', sourceUrl: 'https://t.me/job_react/5120', channelName: 'job_react', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-17T13:45:00.000Z',
      status: 'active',
    },
  ],
  'src-tg-backend': [
    {
      id: 'tg-backend-9102',
      fingerprint: 'tg-backend-9102',
      title: 'Senior Backend Developer (Rust / Highload)',
      company: 'Crypto & Web3 Protocol',
      location: 'Remote',
      isRemote: true,
      experienceLevel: 'Senior',
      employmentType: 'Full-time',
      salary: { from: 6000, to: 8500, currency: 'USD' },
      description: 'We are seeking a Senior Rust Engineer to build core engine components for our decentralized order matching and settlement protocol. The position requires deep knowledge of low-latency networking, lock-free concurrency, and memory optimization.',
      responsibilities: [
        'Design and implement ultra-low latency matching engine services in Rust',
        'Optimize memory layout, CPU cache locality, and zero-copy deserialization',
        'Implement fault-tolerant replication protocols and deterministic state machines',
        'Write high-coverage property-based and fuzzing tests',
      ],
      qualifications: [
        '3+ years of professional Rust development experience (5+ years in backend overall)',
        'Deep mastery of Tokio, async Rust, memory safety, and unsafe Rust invariants',
        'Strong background in high-performance networking (epoll, io_uring, WebSockets, gRPC)',
        'Solid computer science fundamentals (data structures, lock-free algorithms, cache coherence)',
      ],
      niceToHave: [
        'Experience building trading systems, matching engines, or blockchain node clients',
      ],
      benefits: [
        'Competitive compensation in USD/USDT with token grant participation',
        '100% remote flexibility across global time zones',
        'Budget for hardware, conference travels, and books',
      ],
      aboutCompany: 'Next-generation decentralized finance protocol processing billions in trading volume.',
      contactInfo: '@rust_web3_talent',
      requiredSkills: ['Rust', 'Tokio', 'Asynchronous', 'Highload', 'Low Latency', 'PostgreSQL', 'io_uring'],
      url: 'https://t.me/forphptut/9102',
      provenance: { sourceType: 'telegram', sourceId: 'src-tg-backend', sourceUrl: 'https://t.me/forphptut/9102', channelName: 'forphptut', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-17T15:20:00.000Z',
      status: 'active',
    },
  ],
  'src-tg-devops': [
    {
      id: 'tg-devops-4182',
      fingerprint: 'tg-devops-4182',
      title: 'Senior SRE / Infrastructure Engineer',
      company: 'Global Streaming Platform',
      location: 'Remote / Dubai',
      isRemote: true,
      experienceLevel: 'Senior',
      employmentType: 'Full-time',
      salary: { from: 5500, to: 7500, currency: 'USD' },
      description: 'Ищем Senior SRE для поддержки международной платформы видеостриминга. Вы будете проектировать multi-region инфраструктуру в AWS и GCP, настраивать автоматическое масштабирование под прямые трансляции и развивать стек наблюдаемости.',
      responsibilities: [
        'Поддержка и оптимизация multi-region Kubernetes кластеров в AWS (EKS) и GCP (GKE)',
        'Настройка мониторинга, алертинга и трассировки (Grafana, Prometheus, VictoriaMetrics, OpenTelemetry)',
        'Автоматизация инфраструктуры через Terraform и ArgoCD (GitOps)',
        'Участие в дежурствах и расследовании сложных инфраструктурных инцидентов',
      ],
      qualifications: [
        'Опыт работы SRE / DevOps инженером от 4 лет',
        'Глубокие знания Kubernetes, Service Mesh (Istio), Linux networking',
        'Опыт работы с крупными AWS/GCP инсталляциями',
        'Навыки скриптинга и автоматизации на Python или Go',
      ],
      niceToHave: [
        'Опыт работы со стримингом видео (HLS, DASH, WebRTC, CDN caching)',
      ],
      benefits: [
        'Зарплата в валюте (USD/AED) с возможностью релокации в Дубай (визовая поддержка)',
        'Гибкий график и возможность полной удаленной работы',
        'Предоставление MacBook Pro последнего поколения',
      ],
      aboutCompany: 'Глобальная медиа-платформа с аудиторией более 25 млн зрителей по всему миру.',
      contactInfo: '@sre_stream_jobs',
      requiredSkills: ['Kubernetes', 'AWS', 'Terraform', 'Prometheus', 'Grafana', 'SRE', 'Python', 'ArgoCD'],
      url: 'https://t.me/devops_jobs/4182',
      provenance: { sourceType: 'telegram', sourceId: 'src-tg-devops', sourceUrl: 'https://t.me/devops_jobs/4182', channelName: 'devops_jobs', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-17T10:15:00.000Z',
      status: 'active',
    },
  ],
  'src-tg-qa': [
    {
      id: 'tg-qa-3109',
      fingerprint: 'tg-qa-3109',
      title: 'SDET / QA Lead (TypeScript & Playwright)',
      company: 'HealthTech Platform',
      location: 'Remote',
      isRemote: true,
      experienceLevel: 'Lead',
      employmentType: 'Full-time',
      salary: { from: 270000, to: 360000, currency: 'RUR', gross: false },
      description: 'Построение процессов обеспечения качества и автоматизации тестирования с нуля для телемедицинской платформы. Предстоит разрабатывать E2E тесты веб-кабинетов, API тесты и внедрять политики авторегресса в CI/CD.',
      responsibilities: [
        'Проектирование и разработка архитектуры E2E тестов на TypeScript и Playwright',
        'Автоматизация нагрузочного тестирования критических сценариев (k6)',
        'Интеграция тестовых прогонов в GitHub Actions и формирование отчетов Allure',
        'Управление командой тестирования (3 инженера), онбординг и код-ревью',
      ],
      qualifications: [
        'Опыт работы в QA автоматизации от 4 лет на TypeScript / JavaScript',
        'Уверенное владение Playwright, Supertest, Vitest/Jest',
        'Понимание микросервисной архитектуры и опыт тестирования REST и WebSocket API',
        'Опыт настройки CI/CD пайплайнов',
      ],
      niceToHave: [
        'Опыт тестирования систем, соответствующих стандартам защиты персональных данных (152-ФЗ / HIPAA)',
      ],
      benefits: [
        'Полная удаленка, официальное трудоустройство в аккредитованной IT-компании',
        'ДМС со стоматологией и бесплатные консультации врачей сервиса для семьи',
        'Оплата профильных курсов и конференций',
      ],
      aboutCompany: 'Телемедицинская платформа, связывающая пациентов с ведущими профильными врачами в онлайн-формате.',
      contactInfo: '@healthtech_qa_lead',
      requiredSkills: ['QA', 'Playwright', 'TypeScript', 'k6', 'CI/CD', 'API Testing', 'Allure'],
      url: 'https://t.me/qa_jobs/3109',
      provenance: { sourceType: 'telegram', sourceId: 'src-tg-qa', sourceUrl: 'https://t.me/qa_jobs/3109', channelName: 'qa_jobs', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-16T17:30:00.000Z',
      status: 'active',
    },
  ],
  'src-tg-product': [
    {
      id: 'tg-product-6201',
      fingerprint: 'tg-product-6201',
      title: 'Lead Product Manager (AI & Automation)',
      company: 'EdTech Enterprise',
      location: 'Москва / Remote',
      isRemote: true,
      experienceLevel: 'Lead',
      employmentType: 'Full-time',
      salary: { from: 350000, to: 480000, currency: 'RUR', gross: false },
      description: 'Мы ищем Lead Product Manager для запуска и масштабирования генеративных AI-решений в образовательных сервисах. Вы возглавите направление персонализированного обучения, интерактивных тьюторов и автоматической проверки заданий.',
      responsibilities: [
        'Формирование видения и дорожной карты внедрения AI в образовательные продукты',
        'Проведение CustDev исследований и быстрых проверок гипотез с помощью A/B тестов',
        'Управление кросс-функциональной командой из 10+ специалистов (ML инженеры, разработчики, методисты)',
        'Анализ продуктовых и финансовых метрик (LTV, Retention, CAC, юнит-экономика)',
      ],
      qualifications: [
        'Опыт в роли Senior/Lead Product Manager от 4 лет',
        'Понимание возможностей и ограничений современных LLM / GenAI технологий',
        'Сильные аналитические навыки (SQL, когортный анализ, статистика A/B тестов)',
        'Опыт вывода на рынок новых продуктов с нуля до масштабирования',
      ],
      niceToHave: [
        'Опыт работы в EdTech или AI-стартапах',
      ],
      benefits: [
        'Гибкий формат работы: полная удаленка или офис в Москве',
        'Опционная программа и квартальные премии по результатам OKR',
        'Бесплатный доступ ко всем образовательным курсам платформы',
      ],
      aboutCompany: 'Крупнейшая образовательная платформа с более чем 5 млн активных студентов.',
      contactInfo: '@edtech_pm_lead',
      requiredSkills: ['Product Management', 'AI/ML', 'A/B Testing', 'CustDev', 'Metrics', 'Strategy', 'SQL'],
      url: 'https://t.me/product_jobs/6201',
      provenance: { sourceType: 'telegram', sourceId: 'src-tg-product', sourceUrl: 'https://t.me/product_jobs/6201', channelName: 'product_jobs', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-17T09:40:00.000Z',
      status: 'active',
    },
  ],
  'src-tg-datascience': [
    {
      id: 'tg-ds-7312',
      fingerprint: 'tg-ds-7312',
      title: 'Senior LLM / NLP Research Engineer',
      company: 'AI Research Lab',
      location: 'Remote / Belgrade / Dubai',
      isRemote: true,
      experienceLevel: 'Senior',
      employmentType: 'Full-time',
      salary: { from: 6500, to: 9500, currency: 'USD' },
      description: 'Join our applied AI research team working on post-training, alignment, and efficient inference of open-weight LLMs. You will conduct research on instruction tuning, DPO/RLHF, reasoning benchmarks, and long-context scaling.',
      responsibilities: [
        'Research and implement state-of-the-art alignment techniques (SFT, DPO, KTO, RLHF) on LLMs',
        'Optimize multi-GPU training and distributed data pipelines using PyTorch and DeepSpeed/FSDP',
        'Evaluate model capabilities across standard reasoning, coding, and mathematical benchmarks',
        'Build and maintain optimized inference endpoints with vLLM, TensorRT-LLM, and speculative decoding',
      ],
      qualifications: [
        '3+ years of experience in NLP / Deep Learning with PyTorch and Transformers',
        'Demonstrated experience fine-tuning large language models (Llama, Mistral, Qwen)',
        'Strong mathematical foundation in deep learning, loss formulations, and probability theory',
        'Proficiency in Python and CUDA profiling',
      ],
      niceToHave: [
        'Publications at ACL, EMNLP, NeurIPS, or ICLR',
        'Experience with synthetic data generation workflows and agent frameworks',
      ],
      benefits: [
        'Competitive USD compensation with relocation support to Belgrade or Dubai',
        'Uncapped compute access on dedicated H100 clusters',
        'Participation in research publications and open-source releases',
      ],
      aboutCompany: 'Leading independent AI research lab developing cutting-edge foundational and open-source models.',
      contactInfo: '@ai_lab_research_hr',
      requiredSkills: ['Python', 'PyTorch', 'LLMs', 'NLP', 'vLLM', 'Transformers', 'CUDA', 'DeepSpeed'],
      url: 'https://t.me/datasciencejobs/7312',
      provenance: { sourceType: 'telegram', sourceId: 'src-tg-datascience', sourceUrl: 'https://t.me/datasciencejobs/7312', channelName: 'datasciencejobs', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-17T16:00:00.000Z',
      status: 'active',
    },
  ],
  'src-tg-relocate': [
    {
      id: 'tg-relocate-1945',
      fingerprint: 'tg-relocate-1945',
      title: 'Senior Backend Engineer (Go / Java) + Relocation to Germany',
      company: 'Zalando',
      location: 'Berlin, Germany',
      isRemote: false,
      experienceLevel: 'Senior',
      employmentType: 'Full-time',
      salary: { from: 85000, to: 110000, currency: 'EUR' },
      description: 'Zalando is looking for a Senior Backend Engineer to join our European logistics and fulfillment platform team in Berlin. The role comes with full visa sponsorship, Blue Card support, and a comprehensive relocation assistance package for you and your family.',
      responsibilities: [
        'Design and build high-throughput distributed microservices in Go and Java / Spring Boot',
        'Scale asynchronous event-driven pipelines on Apache Kafka and AWS infrastructure',
        'Participate in architecture reviews, on-call rotations, and performance tuning',
        'Collaborate with international cross-functional teams in an English-speaking environment',
      ],
      qualifications: [
        '4+ years of professional backend engineering experience with Go or Java',
        'Solid experience with distributed systems, REST APIs, Kafka, and PostgreSQL / DynamoDB',
        'Experience with Kubernetes, Docker, and AWS cloud services',
        'Fluent English communication skills (minimum B2/C1)',
      ],
      niceToHave: [
        'Prior experience with e-commerce logistics or highload warehouse management systems',
      ],
      benefits: [
        'Full visa sponsorship (EU Blue Card) and premium relocation support (flights, temporary apartment, agency fees)',
        '30 days of paid vacation per year',
        '40% employee discount across the entire Zalando catalog',
        'Public transport ticket subsidy in Berlin and corporate gym membership',
      ],
      aboutCompany: 'Zalando is Europe’s leading online fashion and lifestyle platform connecting millions of customers and partners.',
      contactInfo: '@zalando_relocate_recruiter',
      requiredSkills: ['Go', 'Java', 'Kubernetes', 'Microservices', 'Relocation', 'English', 'Kafka', 'AWS'],
      url: 'https://t.me/relocate_today/1945',
      provenance: { sourceType: 'telegram', sourceId: 'src-tg-relocate', sourceUrl: 'https://t.me/relocate_today/1945', channelName: 'relocate_today', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-17T08:30:00.000Z',
      status: 'active',
    },
  ],
  'src-tg-gamedev': [
    {
      id: 'tg-tg-gamedev-4501',
      fingerprint: 'tg-tg-gamedev-4501',
      title: 'Lead Unity / C# Game Developer',
      company: 'Mobile Gaming Studio (Cyprus)',
      location: 'Remote / Limassol',
      isRemote: true,
      experienceLevel: 'Lead',
      employmentType: 'Full-time',
      salary: { from: 4000, to: 5500, currency: 'EUR' },
      description: 'Ищем Lead Unity разработчика для создания новых мобильных 3D проектов с аудиторией более 10M+ MAU. Вам предстоит руководить клиентской разработкой, оптимизировать рендеринг под мобильные устройства и выстраивать пайплайн сборки.',
      responsibilities: [
        'Проектирование архитектуры мобильного игрового клиента на Unity и C#',
        'Оптимизация шейдеров, рендеринга (URP), памяти и времени загрузки на iOS и Android',
        'Управление командой клиентских разработчиков (4 человека), код-ревью и менторинг',
        'Интеграция рекламных сетей, внутриигровых покупок (IAP) и аналитики',
      ],
      qualifications: [
        'Опыт коммерческой разработки игр на Unity / C# от 5 лет',
        'Глубокие знания оптимизации графики (draw calls, batching, occlusion culling)',
        'Опыт написания кастомных шейдеров (Shader Graph / HLSL)',
        'Опыт выпуска успешных коммерческих мобильных тайтлов',
      ],
      niceToHave: [
        'Опыт работы с multiplayer технологиями (Photon, Mirror) или WebGL билдами',
      ],
      benefits: [
        'Оплата в EUR на зарубежный счет или официальный контракт на Кипре (помощь с визой)',
        'Гибкий график работы и возможность полной удаленки',
        'Годовые роялти-бонусы от прибыли запущенных проектов',
      ],
      aboutCompany: 'Международная студия разработки мобильных игр с офисами на Кипре и распределенной командой по всему миру.',
      contactInfo: '@gamedev_lead_talent',
      requiredSkills: ['Unity', 'C#', 'Shaders', 'Mobile Games', 'Performance', 'Architecture', 'HLSL'],
      url: 'https://t.me/gamedevjob/4501',
      provenance: { sourceType: 'telegram', sourceId: 'src-tg-gamedev', sourceUrl: 'https://t.me/gamedevjob/4501', channelName: 'gamedevjob', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-16T14:10:00.000Z',
      status: 'active',
    },
  ],
};
