import type { UnifiedVacancy } from '../domain/unifiedVacancy';

export const CURATED_SOURCE_VACANCIES: Record<string, UnifiedVacancy[]> = {
  hh: [
    {
      id: 'hh-10823491',
      fingerprint: 'hh-10823491',
      title: 'Senior Frontend Engineer (React/TypeScript)',
      company: 'Яндекс',
      location: 'Москва / Remote',
      isRemote: true,
      salary: { from: 320000, to: 420000, currency: 'RUR', gross: false },
      description: 'Разработка ключевых пользовательских сценариев высоконагруженного сервиса. Стек: React 18, TypeScript, Redux Toolkit, Webpack, Node.js.',
      requiredSkills: ['React', 'TypeScript', 'Node.js', 'Redux', 'Architecture'],
      url: 'https://hh.ru/vacancy/10823491',
      provenance: { sourceType: 'hh', sourceId: 'hh', sourceUrl: 'https://hh.ru/vacancy/10823491', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-17T10:00:00.000Z',
      status: 'active',
    },
    {
      id: 'hh-10829812',
      fingerprint: 'hh-10829812',
      title: 'Lead DevOps / SRE Engineer',
      company: 'Авито',
      location: 'Санкт-Петербург / Hybrid',
      isRemote: false,
      salary: { from: 400000, to: 520000, currency: 'RUR', gross: false },
      description: 'Управление кластерами Kubernetes, CI/CD пайплайнами, мониторингом Prometheus/Grafana и отказоустойчивостью инфраструктуры.',
      requiredSkills: ['Kubernetes', 'Docker', 'Terraform', 'CI/CD', 'Linux', 'Go'],
      url: 'https://hh.ru/vacancy/10829812',
      provenance: { sourceType: 'hh', sourceId: 'hh', sourceUrl: 'https://hh.ru/vacancy/10829812', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-17T11:30:00.000Z',
      status: 'active',
    },
    {
      id: 'hh-10834105',
      fingerprint: 'hh-10834105',
      title: 'Senior Product Manager (B2B SaaS)',
      company: 'Контур',
      location: 'Екатеринбург / Remote',
      isRemote: true,
      salary: { from: 280000, to: 380000, currency: 'RUR', gross: false },
      description: 'Развитие продуктовой линейки для корпоративных клиентов. Юнит-экономика, CustDev, приоритизация бэклога и запуск новых фичей.',
      requiredSkills: ['Product Management', 'CustDev', 'Unit Economics', 'Agile', 'Data Analytics'],
      url: 'https://hh.ru/vacancy/10834105',
      provenance: { sourceType: 'hh', sourceId: 'hh', sourceUrl: 'https://hh.ru/vacancy/10834105', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-16T14:20:00.000Z',
      status: 'active',
    },
  ],
  remotive: [
    {
      id: 'remotive-948102',
      fingerprint: 'remotive-948102',
      title: 'Staff Full-Stack Engineer (Next.js & Node)',
      company: 'GitBook',
      location: 'Worldwide Remote',
      isRemote: true,
      salary: { from: 130000, to: 175000, currency: 'USD' },
      description: 'Scale collaborative knowledge management tools. Work across Next.js, Node.js microservices, GraphQL and PostgreSQL.',
      requiredSkills: ['Next.js', 'TypeScript', 'Node.js', 'PostgreSQL', 'GraphQL', 'AWS'],
      url: 'https://remotive.com/remote-jobs/software-dev/staff-full-stack-engineer-948102',
      provenance: { sourceType: 'remotive', sourceId: 'remotive', sourceUrl: 'https://remotive.com', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-17T08:00:00.000Z',
      status: 'active',
    },
    {
      id: 'remotive-948512',
      fingerprint: 'remotive-948512',
      title: 'Principal Cloud Architect',
      company: 'Automattic',
      location: 'Global Remote',
      isRemote: true,
      salary: { from: 160000, to: 210000, currency: 'USD' },
      description: 'Architect and optimize global distributed systems powering millions of web applications with zero downtime.',
      requiredSkills: ['Cloud Architecture', 'Kubernetes', 'AWS', 'GCP', 'Terraform', 'Distributed Systems'],
      url: 'https://remotive.com/remote-jobs/devops/principal-cloud-architect-948512',
      provenance: { sourceType: 'remotive', sourceId: 'remotive', sourceUrl: 'https://remotive.com', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-16T16:45:00.000Z',
      status: 'active',
    },
  ],
  'src-habr-career': [
    {
      id: 'habr-1000192',
      fingerprint: 'habr-1000192',
      title: 'Senior Backend Developer (Go / Microservices)',
      company: 'Ozon Tech',
      location: 'Москва / Remote',
      isRemote: true,
      salary: { from: 350000, to: 470000, currency: 'RUR', gross: false },
      description: 'Проектирование и разработка высоконагруженных сервисов маркетплейса на Go. Миллионы RPS, Kafka, PostgreSQL, gRPC.',
      requiredSkills: ['Go', 'Golang', 'PostgreSQL', 'Kafka', 'gRPC', 'Docker', 'Redis'],
      url: 'https://career.habr.com/vacancies/1000192',
      provenance: { sourceType: 'rss', sourceId: 'src-habr-career', sourceUrl: 'https://career.habr.com', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-17T09:15:00.000Z',
      status: 'active',
    },
    {
      id: 'habr-1000244',
      fingerprint: 'habr-1000244',
      title: 'Lead QA Automation Engineer (Python / Playwright)',
      company: 'VK',
      location: 'Санкт-Петербург / Remote',
      isRemote: true,
      salary: { from: 260000, to: 340000, currency: 'RUR', gross: false },
      description: 'Построение фреймворка сквозного E2E тестирования веб и мобильных сервисов. CI/CD интеграция, отчетность Allure.',
      requiredSkills: ['Python', 'Playwright', 'Selenium', 'CI/CD', 'API Testing', 'Docker'],
      url: 'https://career.habr.com/vacancies/1000244',
      provenance: { sourceType: 'rss', sourceId: 'src-habr-career', sourceUrl: 'https://career.habr.com', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-16T12:00:00.000Z',
      status: 'active',
    },
  ],
  'src-superjob': [
    {
      id: 'superjob-489102',
      fingerprint: 'superjob-489102',
      title: 'Архитектор программных решений / Enterprise Architect',
      company: 'СберТех',
      location: 'Москва',
      isRemote: false,
      salary: { from: 450000, to: 600000, currency: 'RUR', gross: true },
      description: 'Разработка архитектурной стратегии цифровой платформы, стандартизация технологического стека, ревью крупных решений.',
      requiredSkills: ['Enterprise Architecture', 'Java', 'Spring', 'Kafka', 'Security', 'SOA'],
      url: 'https://superjob.ru/vakansii/489102',
      provenance: { sourceType: 'rss', sourceId: 'src-superjob', sourceUrl: 'https://superjob.ru', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-16T15:00:00.000Z',
      status: 'active',
    },
  ],
  'src-zarplata': [
    {
      id: 'zarplata-391029',
      fingerprint: 'zarplata-391029',
      title: 'Senior Python / Django разработчик',
      company: 'Сибирские Цифровые Технологии',
      location: 'Новосибирск / Remote',
      isRemote: true,
      salary: { from: 240000, to: 310000, currency: 'RUR', gross: false },
      description: 'Разработка внутренних продуктов для автоматизации логистики. FastAPI, Django REST, Celery, PostgreSQL.',
      requiredSkills: ['Python', 'Django', 'FastAPI', 'PostgreSQL', 'Docker', 'Redis'],
      url: 'https://zarplata.ru/vacancy/391029',
      provenance: { sourceType: 'rss', sourceId: 'src-zarplata', sourceUrl: 'https://zarplata.ru', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-17T07:30:00.000Z',
      status: 'active',
    },
  ],
  'src-trudvsem': [
    {
      id: 'trudvsem-819201',
      fingerprint: 'trudvsem-819201',
      title: 'Инженер по защите информации и кибербезопасности',
      company: 'ГосТех / НИИ',
      location: 'Москва / Гибрид',
      isRemote: false,
      salary: { from: 220000, to: 290000, currency: 'RUR', gross: false },
      description: 'Аудит информационной безопасности, анализ уязвимостей, внедрение мер защиты в соответствии со стандартами.',
      requiredSkills: ['Cybersecurity', 'SIEM', 'Network Security', 'Linux', 'Audit'],
      url: 'https://trudvsem.ru/vacancy/819201',
      provenance: { sourceType: 'rss', sourceId: 'src-trudvsem', sourceUrl: 'https://trudvsem.ru', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-15T11:00:00.000Z',
      status: 'active',
    },
  ],
  'src-weworkremotely': [
    {
      id: 'wwr-772910',
      fingerprint: 'wwr-772910',
      title: 'Senior React / Design Systems Engineer',
      company: 'Hotjar',
      location: 'Remote (EU / Americas)',
      isRemote: true,
      salary: { from: 110000, to: 145000, currency: 'USD' },
      description: 'Build and maintain our core design system component library with a focus on accessibility, tokens, and DX.',
      requiredSkills: ['React', 'TypeScript', 'CSS', 'Storybook', 'Accessibility', 'Figma'],
      url: 'https://weworkremotely.com/jobs/772910',
      provenance: { sourceType: 'rss', sourceId: 'src-weworkremotely', sourceUrl: 'https://weworkremotely.com', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-17T13:00:00.000Z',
      status: 'active',
    },
  ],
  'src-remoteok': [
    {
      id: 'remoteok-55102',
      fingerprint: 'remoteok-55102',
      title: 'Head of Data Science / ML Platform',
      company: 'Runway ML',
      location: 'Anywhere in the World',
      isRemote: true,
      salary: { from: 180000, to: 240000, currency: 'USD' },
      description: 'Lead research and deployment of foundation generative AI models at global scale.',
      requiredSkills: ['Python', 'PyTorch', 'Machine Learning', 'LLMs', 'MLOps', 'CUDA'],
      url: 'https://remoteok.com/remote-jobs/55102',
      provenance: { sourceType: 'rss', sourceId: 'src-remoteok', sourceUrl: 'https://remoteok.com', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-16T19:00:00.000Z',
      status: 'active',
    },
  ],
  'src-tg-itjobs': [
    {
      id: 'tg-itjobs-14902',
      fingerprint: 'tg-itjobs-14902',
      title: 'Senior Node.js / TypeScript Developer',
      company: 'Fintech Startup (Cyprus/Remote)',
      location: 'Remote',
      isRemote: true,
      salary: { from: 4500, to: 6000, currency: 'USD' },
      description: 'Ищем опытного бэкендера в международный финтех. Стек: Node.js, TypeScript, PostgreSQL, NestJS, AWS, Kafka.',
      requiredSkills: ['Node.js', 'TypeScript', 'NestJS', 'PostgreSQL', 'Kafka', 'AWS'],
      url: 'https://t.me/it_jobs/14902',
      provenance: { sourceType: 'telegram', sourceId: 'src-tg-itjobs', sourceUrl: 'https://t.me/it_jobs/14902', channelName: 'it_jobs', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-17T14:10:00.000Z',
      status: 'active',
    },
    {
      id: 'tg-itjobs-14905',
      fingerprint: 'tg-itjobs-14905',
      title: 'Engineering Manager (Core Services)',
      company: 'E-commerce Platform',
      location: 'Москва / Remote',
      isRemote: true,
      salary: { from: 380000, to: 480000, currency: 'RUR', gross: false },
      description: 'Управление командой из 12 разработчиков, найм, 1-on-1, синхронизация с продуктовым отделом, улучшение метрик DORA.',
      requiredSkills: ['Engineering Management', 'Leadership', 'Agile', 'System Architecture', 'Mentorship'],
      url: 'https://t.me/it_jobs/14905',
      provenance: { sourceType: 'telegram', sourceId: 'src-tg-itjobs', sourceUrl: 'https://t.me/it_jobs/14905', channelName: 'it_jobs', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-17T12:00:00.000Z',
      status: 'active',
    },
  ],
  'src-tg-tproger': [
    {
      id: 'tg-tproger-8841',
      fingerprint: 'tg-tproger-8841',
      title: 'Team Lead Fullstack (React + Go)',
      company: 'T-Bank / Т-Банк',
      location: 'Москва / Remote',
      isRemote: true,
      salary: { from: 420000, to: 550000, currency: 'RUR', gross: false },
      description: 'Руководство разработкой платежных интерфейсов и шлюзов. Стек: Go, React, Kafka, ClickHouse, Docker.',
      requiredSkills: ['Go', 'React', 'TypeScript', 'Team Lead', 'Kafka', 'Highload'],
      url: 'https://t.me/tproger_jobs/8841',
      provenance: { sourceType: 'telegram', sourceId: 'src-tg-tproger', sourceUrl: 'https://t.me/tproger_jobs/8841', channelName: 'tproger_jobs', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-17T11:00:00.000Z',
      status: 'active',
    },
  ],
  'src-tg-react': [
    {
      id: 'tg-react-5120',
      fingerprint: 'tg-react-5120',
      title: 'Senior Frontend Developer (React 19 / Next.js)',
      company: 'AdTech Agency',
      location: 'Remote',
      isRemote: true,
      salary: { from: 300000, to: 400000, currency: 'RUR', gross: false },
      description: 'Разработка интерактивных дэшбордов аналитики рекламы. React 19, TailwindCSS / CSS Modules, WebGL графики.',
      requiredSkills: ['React', 'Next.js', 'TypeScript', 'Performance', 'WebGL', 'Zustand'],
      url: 'https://t.me/job_react/5120',
      provenance: { sourceType: 'telegram', sourceId: 'src-tg-react', sourceUrl: 'https://t.me/job_react/5120', channelName: 'job_react', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-17T13:45:00.000Z',
      status: 'active',
    },
  ],
  'src-tg-backend': [
    {
      id: 'tg-backend-9102',
      fingerprint: 'tg-backend-9102',
      title: 'Senior Backend Developer (Rust / Highload)',
      company: 'Crypto & Web3 Protocol',
      location: 'Remote',
      isRemote: true,
      salary: { from: 6000, to: 8500, currency: 'USD' },
      description: 'Core engine development in Rust for decentralized order matching engine. Low latency, memory safety, async tokio.',
      requiredSkills: ['Rust', 'Tokio', 'Asynchronous', 'Highload', 'Low Latency', 'PostgreSQL'],
      url: 'https://t.me/forphptut/9102',
      provenance: { sourceType: 'telegram', sourceId: 'src-tg-backend', sourceUrl: 'https://t.me/forphptut/9102', channelName: 'forphptut', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-17T15:20:00.000Z',
      status: 'active',
    },
  ],
  'src-tg-devops': [
    {
      id: 'tg-devops-4182',
      fingerprint: 'tg-devops-4182',
      title: 'Senior SRE / Infrastructure Engineer',
      company: 'Global Streaming Platform',
      location: 'Remote / Dubai',
      isRemote: true,
      salary: { from: 5500, to: 7500, currency: 'USD' },
      description: 'Multi-region AWS/GCP infrastructure, Kubernetes operator management, Chaos engineering, Grafana Mimir/Loki.',
      requiredSkills: ['Kubernetes', 'AWS', 'Terraform', 'Prometheus', 'Grafana', 'SRE', 'Python'],
      url: 'https://t.me/devops_jobs/4182',
      provenance: { sourceType: 'telegram', sourceId: 'src-tg-devops', sourceUrl: 'https://t.me/devops_jobs/4182', channelName: 'devops_jobs', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-17T10:15:00.000Z',
      status: 'active',
    },
  ],
  'src-tg-qa': [
    {
      id: 'tg-qa-3109',
      fingerprint: 'tg-qa-3109',
      title: 'SDET / QA Lead (TypeScript & Playwright)',
      company: 'HealthTech Platform',
      location: 'Remote',
      isRemote: true,
      salary: { from: 270000, to: 360000, currency: 'RUR', gross: false },
      description: 'Построение автоматизации тестирования с нуля: API (Supertest/Jest), UI (Playwright), нагрузочное тестирование (k6).',
      requiredSkills: ['QA', 'Playwright', 'TypeScript', 'k6', 'CI/CD', 'API Testing'],
      url: 'https://t.me/qa_jobs/3109',
      provenance: { sourceType: 'telegram', sourceId: 'src-tg-qa', sourceUrl: 'https://t.me/qa_jobs/3109', channelName: 'qa_jobs', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-16T17:30:00.000Z',
      status: 'active',
    },
  ],
  'src-tg-product': [
    {
      id: 'tg-product-6201',
      fingerprint: 'tg-product-6201',
      title: 'Lead Product Manager (AI & Automation)',
      company: 'EdTech Enterprise',
      location: 'Москва / Remote',
      isRemote: true,
      salary: { from: 350000, to: 480000, currency: 'RUR', gross: false },
      description: 'Запуск и масштабирование AI-ассистентов в образовательных продуктах. Проверка гипотез, A/B тестирование, экономика.',
      requiredSkills: ['Product Management', 'AI/ML', 'A/B Testing', 'CustDev', 'Metrics', 'Strategy'],
      url: 'https://t.me/product_jobs/6201',
      provenance: { sourceType: 'telegram', sourceId: 'src-tg-product', sourceUrl: 'https://t.me/product_jobs/6201', channelName: 'product_jobs', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-17T09:40:00.000Z',
      status: 'active',
    },
  ],
  'src-tg-datascience': [
    {
      id: 'tg-ds-7312',
      fingerprint: 'tg-ds-7312',
      title: 'Senior LLM / NLP Research Engineer',
      company: 'AI Research Lab',
      location: 'Remote / Belgrade / Dubai',
      isRemote: true,
      salary: { from: 6500, to: 9500, currency: 'USD' },
      description: 'Fine-tuning, RLHF and evaluation of open-weight LLMs (Llama, Mistral, Qwen). Deep learning in PyTorch and vLLM.',
      requiredSkills: ['Python', 'PyTorch', 'LLMs', 'NLP', 'vLLM', 'Transformers', 'CUDA'],
      url: 'https://t.me/datasciencejobs/7312',
      provenance: { sourceType: 'telegram', sourceId: 'src-tg-datascience', sourceUrl: 'https://t.me/datasciencejobs/7312', channelName: 'datasciencejobs', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-17T16:00:00.000Z',
      status: 'active',
    },
  ],
  'src-tg-relocate': [
    {
      id: 'tg-relocate-1892',
      fingerprint: 'tg-relocate-1892',
      title: 'Senior Backend Engineer (Go / Java) + Relocation to Germany',
      company: 'Zalando',
      location: 'Berlin, Germany',
      isRemote: false,
      salary: { from: 85000, to: 110000, currency: 'EUR' },
      description: 'Join Berlin engineering team with full visa sponsorship and relocation support package. High-scale microservices.',
      requiredSkills: ['Go', 'Java', 'Kubernetes', 'Microservices', 'Relocation', 'English'],
      url: 'https://t.me/relocate_today/1892',
      provenance: { sourceType: 'telegram', sourceId: 'src-tg-relocate', sourceUrl: 'https://t.me/relocate_today/1892', channelName: 'relocate_today', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-17T08:30:00.000Z',
      status: 'active',
    },
  ],
  'src-tg-gamedev': [
    {
      id: 'tg-gamedev-4501',
      fingerprint: 'tg-gamedev-4501',
      title: 'Lead Unity / C# Game Developer',
      company: 'Mobile Gaming Studio (Cyprus)',
      location: 'Remote / Limassol',
      isRemote: true,
      salary: { from: 4000, to: 5500, currency: 'EUR' },
      description: 'Разработка мобильных игр с аудиторией 10M+ MAU. Архитектура клиента, шейдеры, оптимизация памяти и рендеринга.',
      requiredSkills: ['Unity', 'C#', 'Shaders', 'Mobile Games', 'Performance', 'Architecture'],
      url: 'https://t.me/gamedevjob/4501',
      provenance: { sourceType: 'telegram', sourceId: 'src-tg-gamedev', sourceUrl: 'https://t.me/gamedevjob/4501', channelName: 'gamedevjob', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-16T14:10:00.000Z',
      status: 'active',
    },
  ],
};
