import type { UnifiedVacancy } from '../domain/unifiedVacancy';

export const CURATED_PLATFORM_VACANCIES: Record<string, UnifiedVacancy[]> = {
  hh: [
    {
      id: 'hh-10823491',
      fingerprint: 'hh-10823491',
      title: 'Senior Frontend Engineer (React / TypeScript)',
      company: 'Яндекс',
      location: 'Москва / Remote',
      isRemote: true,
      experienceLevel: 'Senior',
      employmentType: 'Full-time',
      salary: { from: 320000, to: 420000, currency: 'RUR', gross: false },
      description: 'Ищем Senior Frontend разработчика в команду поисковых интерфейсов и контентных сервисов. Вам предстоит работать над ключевыми экранами с аудиторией более 40 млн пользователей в день, разрабатывать быстрые и отказоустойчивые веб-приложения на React и TypeScript.',
      responsibilities: [
        'Разработка и оптимизация высоконагруженных клиентских интерфейсов на React 18+ и TypeScript',
        'Проектирование архитектуры переиспользуемых модулей и дизайн-системы компонентов',
        'Оптимизация Core Web Vitals (LCP, INP, CLS) и времени рендеринга на мобильных устройствах',
        'Участие в проектировании API взаимодействия между клиентом и бэкенд-микросервисами',
        'Проведение код-ревью, менторинг Middle разработчиков и внедрение инженерных практик',
      ],
      qualifications: [
        'Опыт коммерческой разработки на React и TypeScript от 4 лет',
        'Глубокое понимание внутреннего устройства React (Fiber, Reconciliation, Concurrent Mode)',
        'Уверенное владение современным CSS, CSS-переменными, доступностью (a11y) и версткой под разные экраны',
        'Опыт профилирования производительности в Chrome DevTools и снижения объема JS-бандлов',
        'Практический опыт написания Unit и E2E тестов (Vitest, Jest, Playwright)',
      ],
      niceToHave: [
        'Опыт работы с Server-Side Rendering (Next.js, Remix) и микрофронтендами',
        'Опыт участия в Open Source проектах или разработке UI-китов',
      ],
      benefits: [
        'Гибкий график и возможность работать полностью удаленно или в комфортных офисах в РФ и за рубежом',
        'Расширенный ДМС со стоматологией с первого месяца работы',
        'Предоставление мощной техники на выбор (MacBook Pro M3/M4)',
        'Корпоративные программы обучения, компенсация конференций и профильных курсов',
        'Годовые премии и опционная программа по результатам ревью',
      ],
      aboutCompany: 'Яндекс — одна из крупнейших технологических компаний, создающая интеллектуальные продукты и сервисы на основе машинного обучения для миллионов пользователей.',
      contactInfo: 'hr-search@yandex-team.ru',
      requiredSkills: ['React', 'TypeScript', 'Node.js', 'Redux Toolkit', 'Performance', 'Playwright'],
      url: 'https://hh.ru/vacancy/10823491',
      provenance: { sourceType: 'hh', sourceId: 'hh', sourceUrl: 'https://hh.ru/vacancy/10823491', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-17T10:00:00.000Z',
      status: 'active',
    },
    {
      id: 'hh-10829812',
      fingerprint: 'hh-10829812',
      title: 'Lead DevOps / SRE Engineer',
      company: 'Авито',
      location: 'Санкт-Петербург / Hybrid',
      isRemote: false,
      experienceLevel: 'Lead',
      employmentType: 'Full-time',
      salary: { from: 400000, to: 520000, currency: 'RUR', gross: false },
      description: 'Команда инфраструктуры Авито ищет Lead DevOps / SRE инженера для руководства направлением платформенной надежности. Предстоит масштабировать кластеры Kubernetes, развивать Service Mesh и обеспечивать 99.99% доступность ключевых сервисов маркетплейса.',
      responsibilities: [
        'Техническое лидерство группы инженеров надежности (SRE) и платформы доставки (CI/CD)',
        'Проектирование и эксплуатация multi-cluster Kubernetes инфраструктуры (более 5 000 нод)',
        'Внедрение практик Chaos Engineering, определение SLO/SLI и организация дежурств',
        'Автоматизация инфраструктуры с помощью Terraform, Ansible и кастомных K8s-операторов на Go',
        'Управление инцидентами, проведение безнаказанных Post-Mortem ревью и устранение корневых причин сбоев',
      ],
      qualifications: [
        'Опыт работы в роли Senior/Lead DevOps или SRE в высоконагруженных проектах от 5 лет',
        'Глубокие знания Linux internals, сетевых протоколов (TCP/IP, BGP, eBPF) и безопасности',
        'Экспертиза в Kubernetes, Istio/Cilium, Prometheus, Grafana, VictoriaMetrics',
        'Уверенный навык программирования на Go или Python для создания внутренней автоматизации',
        'Опыт управления распределенными хранилищами и брокерами (PostgreSQL, Kafka, ClickHouse)',
      ],
      niceToHave: [
        'Опыт работы с FinOps и оптимизацией затрат на облачную и bare-metal инфраструктуру',
        'Публичные выступления на профильных конференциях (HighLoad++, DevOpsConf)',
      ],
      benefits: [
        'Гибридный формат работы с офисом в центре Санкт-Петербурга с панорамным видом',
        'ДМС с премиальным обслуживанием и страхованием родственников',
        'Бюджет на самообразование 200 000 руб./год и оплата участия в международных конференциях',
        'Компенсация питания, фитнеса и бесплатные парковочные места',
      ],
      aboutCompany: 'Авито — самый популярный сервис объявлений в мире с более чем 60 млн активных пользователей в месяц.',
      contactInfo: 'sre-recruiting@avito.ru',
      requiredSkills: ['Kubernetes', 'Docker', 'Terraform', 'CI/CD', 'Linux', 'Go', 'SRE', 'Prometheus'],
      url: 'https://hh.ru/vacancy/10829812',
      provenance: { sourceType: 'hh', sourceId: 'hh', sourceUrl: 'https://hh.ru/vacancy/10829812', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-17T11:30:00.000Z',
      status: 'active',
    },
    {
      id: 'hh-10834105',
      fingerprint: 'hh-10834105',
      title: 'Senior Product Manager (B2B SaaS)',
      company: 'Контур',
      location: 'Екатеринбург / Remote',
      isRemote: true,
      experienceLevel: 'Senior',
      employmentType: 'Full-time',
      salary: { from: 280000, to: 380000, currency: 'RUR', gross: false },
      description: 'Ищем Senior Product Manager для развития экосистемы электронного документооборота и комплаенс-сервисов для enterprise-клиентов. Ваша цель — кратный рост метрик удержания (NDR) и запуск новых автоматизированных сценариев для бизнеса.',
      responsibilities: [
        'Формирование продуктовой стратегии и квартального roadmap на основе анализа рынка и CustDev',
        'Проведение качественных и количественных исследований с ЛПР крупного бизнеса',
        'Управление полным жизненным циклом фичей от гипотезы до релиза и анализа метрик',
        'Совместная работа с кросс-функциональной командой разработки (15+ инженеров, дизайнеров и аналитиков)',
        'Оптимизация воронки онбординга, монетизации и расчет юнит-экономики',
      ],
      qualifications: [
        'Опыт работы в роли Product Manager в B2B SaaS продуктах от 3.5 лет',
        'Умение аргументировать решения данными (SQL, Amplitude, Tableau/PowerBI, когортный анализ)',
        'Опыт проведения глубинных интервью и тестирования ценностных предложений',
        'Понимание технического устройства веб-сервисов, REST API и интеграционных шлюзов',
      ],
      niceToHave: [
        'Опыт в FinTech, LegalTech или системах ЭДО',
        'Опыт масштабирования продуктов на enterprise-сегмент',
      ],
      benefits: [
        'Полностью удаленная работа из любой точки РФ',
        'Прозрачная система грейдов и регулярный пересмотр вознаграждения',
        'ДМС со стоматологией, психотерапией и массажем',
        'Корпоративный университет Контура и доступ к менторам индустрии',
      ],
      aboutCompany: 'СКБ Контур — экосистема для бизнеса, помогающая миллионам компаний автоматизировать отчетность, учет и безопасность.',
      contactInfo: 'product-careers@kontur.ru',
      requiredSkills: ['Product Management', 'CustDev', 'Unit Economics', 'Agile', 'Data Analytics', 'SQL'],
      url: 'https://hh.ru/vacancy/10834105',
      provenance: { sourceType: 'hh', sourceId: 'hh', sourceUrl: 'https://hh.ru/vacancy/10834105', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-16T14:20:00.000Z',
      status: 'active',
    },
  ],
  remotive: [
    {
      id: 'remotive-948102',
      fingerprint: 'remotive-948102',
      title: 'Staff Full-Stack Engineer (Next.js & Node)',
      company: 'GitBook',
      location: 'Worldwide Remote',
      isRemote: true,
      experienceLevel: 'Lead',
      employmentType: 'Full-time',
      salary: { from: 130000, to: 175000, currency: 'USD' },
      description: 'GitBook is looking for a Staff Full-Stack Engineer to scale our collaborative knowledge platform used by over 500k developers. You will lead the architecture of real-time editing features, offline synchronization, and extensible plugin integrations.',
      responsibilities: [
        'Lead architectural decisions for real-time collaborative document editing engines (CRDTs / Operational Transformation)',
        'Build high-performance web applications using React 19, Next.js, and TypeScript',
        'Design resilient Node.js microservices backed by PostgreSQL, Redis, and Kafka',
        'Champion engineering excellence, zero-regression CI/CD deployment pipelines, and observability',
        'Collaborate directly with Product, Design, and Developer Relations teams to shape product vision',
      ],
      qualifications: [
        '6+ years of full-stack software development experience with modern JavaScript / TypeScript ecosystems',
        'Deep expertise in React architecture, state management, web performance, and browser APIs',
        'Proven track record building and operating distributed backend systems in cloud environments (AWS / GCP)',
        'Experience with distributed real-time systems, WebSockets, and database schema migrations at scale',
        'Exceptional written communication skills in an asynchronous, remote-first team',
      ],
      niceToHave: [
        'Experience building developer tools, CLI utilities, or markdown processing engines',
        'Active open-source contributions',
      ],
      benefits: [
        '100% remote-first culture with asynchronous workflows across worldwide time zones',
        'Competitive equity package (Stock Options) and annual performance bonuses',
        '$4,000 home office setup allowance + $1,500 annual learning & development stipend',
        'Unlimited paid time off (minimum 25 days encouraged per year)',
        'Annual company retreats in beautiful destinations worldwide',
      ],
      aboutCompany: 'GitBook is the modern documentation platform where technical teams build, publish, and collaborate on knowledge effortlessly.',
      contactInfo: 'careers@gitbook.com',
      requiredSkills: ['Next.js', 'TypeScript', 'Node.js', 'PostgreSQL', 'GraphQL', 'AWS', 'WebSockets'],
      url: 'https://remotive.com/remote-jobs/software-dev/staff-full-stack-engineer-948102',
      provenance: { sourceType: 'remotive', sourceId: 'remotive', sourceUrl: 'https://remotive.com', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-17T08:00:00.000Z',
      status: 'active',
    },
    {
      id: 'remotive-948512',
      fingerprint: 'remotive-948512',
      title: 'Principal Cloud Architect',
      company: 'Automattic',
      location: 'Global Remote',
      isRemote: true,
      experienceLevel: 'Principal / Staff',
      employmentType: 'Full-time',
      salary: { from: 160000, to: 210000, currency: 'USD' },
      description: 'Automattic is seeking a Principal Cloud Architect to design and optimize global cloud infrastructure powering WordPress.com, WooCommerce, and Tumblr, serving billions of pageviews every month with high availability and security.',
      responsibilities: [
        'Architect scalable, multi-region hybrid cloud infrastructure across AWS, GCP, and bare-metal datacenters',
        'Drive infrastructure cost optimization strategies, reducing multi-million dollar annual cloud spend',
        'Lead disaster recovery, edge networking (Anycast, Cloudflare, CDN), and zero-trust security initiatives',
        'Partner with core engineering leads to ensure services are resilient against sudden 10x traffic spikes',
        'Mentor principal and senior engineers across the global organization',
      ],
      qualifications: [
        '8+ years in cloud infrastructure architecture, distributed systems, and site reliability at hyper-scale',
        'Deep mastery of Kubernetes, Terraform, Infrastructure as Code, and Linux kernel tuning',
        'Extensive experience with large-scale database clusters (MySQL/Vitess, PostgreSQL, Cassandra, Elasticsearch)',
        'Strong programming background in Go, Python, or Rust for systems automation',
      ],
      niceToHave: [
        'Prior experience operating open-source ecosystems at Internet scale',
        'Published papers or keynotes on distributed cloud topology and edge computing',
      ],
      benefits: [
        'Work from anywhere in the world — Automattic has been 100% distributed since 2005',
        'Open vacation policy and paid sabbaticals every 5 years',
        'Home office setup and monthly coworking allowance',
        'Top-tier health, dental, and vision insurance with global coverage',
      ],
      aboutCompany: 'Automattic is a distributed company dedicated to making the web a better place through WordPress, WooCommerce, Tumblr, and Day One.',
      contactInfo: 'talent@automattic.com',
      requiredSkills: ['Cloud Architecture', 'Kubernetes', 'AWS', 'GCP', 'Terraform', 'Distributed Systems', 'Go'],
      url: 'https://remotive.com/remote-jobs/devops/principal-cloud-architect-948512',
      provenance: { sourceType: 'remotive', sourceId: 'remotive', sourceUrl: 'https://remotive.com', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-16T16:45:00.000Z',
      status: 'active',
    },
  ],
  'src-habr-career': [
    {
      id: 'habr-1000192',
      fingerprint: 'habr-1000192',
      title: 'Senior Backend Developer (Go / Microservices)',
      company: 'Ozon Tech',
      location: 'Москва / Remote',
      isRemote: true,
      experienceLevel: 'Senior',
      employmentType: 'Full-time',
      salary: { from: 350000, to: 470000, currency: 'RUR', gross: false },
      description: 'Команда логистики и фулфилмента Ozon Tech ищет Senior Go разработчика. Вам предстоит проектировать отказоустойчивые микросервисы, обрабатывающие сотни тысяч заказов в минуту, оптимизировать latency в gRPC-вызовах и работать с шардированными базами данных.',
      responsibilities: [
        'Разработка высоконагруженных сервисов на Go (миллионы RPS, критичные SLA)',
        'Проектирование архитектуры взаимодействия через gRPC, Kafka и REST',
        'Оптимизация использования памяти и процессорного времени (pprof, go-torch)',
        'Работа с шардированными кластерами PostgreSQL, Redis и ClickHouse',
        'Участие в проектировании отказоустойчивости сервисов и проведении нагрузочного тестирования',
      ],
      qualifications: [
        'Опыт коммерческой разработки на Go от 3.5 лет',
        'Глубокое понимание concurrency, garbage collector, memory management в Go',
        'Опыт работы с реляционными СУБД (PostgreSQL) и оптимизации сложных SQL-запросов',
        'Уверенное понимание паттернов построения распределенных систем и transactional outbox',
      ],
      niceToHave: [
        'Опыт работы в e-commerce или highload финтех-проектах',
        'Опыт написания кастомных бенчмарков и k6 сценариев',
      ],
      benefits: [
        'Удаленная работа или гибрид с современным офисом в Москва-Сити',
        'ДМС со стоматологией с первого рабочего дня + страховка для путешествий',
        'Скидки на платформе Ozon и партнерские программы',
        'Мощный ноутбук (MacBook Pro / ThinkPad) и мониторы для дома',
      ],
      aboutCompany: 'Ozon Tech — технологическое сердце одного из крупнейших маркетплейсов в СНГ с более чем 500 микросервисами.',
      contactInfo: 'tech-jobs@ozon.ru',
      requiredSkills: ['Go', 'Golang', 'PostgreSQL', 'Kafka', 'gRPC', 'Docker', 'Redis', 'Highload'],
      url: 'https://career.habr.com/vacancies/1000192',
      provenance: { sourceType: 'rss', sourceId: 'src-habr-career', sourceUrl: 'https://career.habr.com', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-17T09:15:00.000Z',
      status: 'active',
    },
    {
      id: 'habr-1000244',
      fingerprint: 'habr-1000244',
      title: 'Lead QA Automation Engineer (Python / Playwright)',
      company: 'VK',
      location: 'Санкт-Петербург / Remote',
      isRemote: true,
      experienceLevel: 'Lead',
      employmentType: 'Full-time',
      salary: { from: 260000, to: 340000, currency: 'RUR', gross: false },
      description: 'Ищем Lead QA Automation инженера в департамент коммуникационных платформ VK. Вы возглавите автоматизацию тестирования веб и десктоп сервисов, построите надежный пайплайн регресса и внедрите стандарты автотестирования для 30+ инженеров.',
      responsibilities: [
        'Разработка и развитие фреймворка сквозного E2E тестирования на Python и Playwright',
        'Интеграция тестов в GitLab CI / Jenkins с параллельным запуском в Docker-контейнерах',
        'Автоматизация API (REST, GraphQL, WebSocket) и UI регрессионного тестирования',
        'Разработка дашбордов качества в Allure Report и мониторинг метрик стабильности тестов',
        'Менторинг команды тестировщиков и обучение практикам написания надежных тестов',
      ],
      qualifications: [
        'Опыт автоматизации тестирования на Python от 4 лет',
        'Экспертное владение Playwright / Selenium WebDriver и pytest',
        'Опыт построения CI/CD пайплайнов с нуля и оптимизации времени прогона тестов',
        'Уверенное знание протоколов HTTP, WebSocket, JSON, формата API-контрактов OpenAPI',
      ],
      niceToHave: [
        'Опыт нагрузочного тестирования с Locust или k6',
        'Опыт работы с мобильной автоматизацией (Appium)',
      ],
      benefits: [
        'Гибкий формат работы: полная удаленка или комфортные офисы в Москве, Санкт-Петербурге, Сочи',
        'Программа заботы о здоровье: ДМС, консультации психологов, спортзал в офисе',
        'Корпоративные льготы экосистемы VK (VK Музыка, VK Combo, образовательные платформы)',
      ],
      aboutCompany: 'VK — крупнейшая российская технологическая компания, объединяющая социальные сети, медиасервисы, игры и образовательные платформы.',
      contactInfo: 'qa-careers@vk.team',
      requiredSkills: ['Python', 'Playwright', 'Selenium', 'CI/CD', 'API Testing', 'Docker', 'pytest'],
      url: 'https://career.habr.com/vacancies/1000244',
      provenance: { sourceType: 'rss', sourceId: 'src-habr-career', sourceUrl: 'https://career.habr.com', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-16T12:00:00.000Z',
      status: 'active',
    },
  ],
  'src-superjob': [
    {
      id: 'superjob-489102',
      fingerprint: 'superjob-489102',
      title: 'Архитектор программных решений / Enterprise Architect',
      company: 'СберТех',
      location: 'Москва',
      isRemote: false,
      experienceLevel: 'Executive',
      employmentType: 'Full-time',
      salary: { from: 450000, to: 600000, currency: 'RUR', gross: true },
      description: 'СберТех ищет Enterprise-архитектора для проектирования целевой архитектуры базовых компонентов цифровой платформы Platform V. Предстоит гармонизировать технологический стек сотен команд и обеспечивать импортонезависимость критической инфраструктуры.',
      responsibilities: [
        'Разработка и аудит архитектурных стандартов и концепций для крупномасштабных сервисов',
        'Участие в архитектурных комитетах и валидация решений проектных команд',
        'Проектирование отказоустойчивых интеграций на базе брокеров сообщений и распределенных СУБД',
        'Устранение технологического долга и разработка планов миграции с легаси-систем',
      ],
      qualifications: [
        'Опыт работы архитектором программного обеспечения в крупных корпорациях от 5 лет',
        'Глубокое знание Java-стека (Spring Boot, Spring Cloud, Hibernate), микросервисной архитектуры',
        'Опыт проектирования SOA, EDA, CQRS и Event Sourcing архитектур',
        'Понимание стандартов информационной безопасности и защиты банковских данных',
      ],
      niceToHave: [
        'Сертификаты TOGAF / AWS Certified Solutions Architect',
        'Опыт работы с отечественными СУБД (Postgres Pro, Arenadata)',
      ],
      benefits: [
        'Работа в современном офисе на Кутузовском проспекте (Agile Home)',
        'Льготная ипотека для сотрудников и корпоративная пенсионная программа',
        'ДМС с первого дня с лучшими клиниками Москвы, включая стоматологию',
        'Годовой бонус в размере нескольких окладов по результатам выполнения КПЭ',
      ],
      aboutCompany: 'СберТех — ведущий российский разработчик программного обеспечения для банковского и корпоративного сектора.',
      contactInfo: 'architects@sbertech.ru',
      requiredSkills: ['Enterprise Architecture', 'Java', 'Spring', 'Kafka', 'Security', 'SOA', 'PostgreSQL'],
      url: 'https://superjob.ru/vakansii/489102',
      provenance: { sourceType: 'rss', sourceId: 'src-superjob', sourceUrl: 'https://superjob.ru', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-16T15:00:00.000Z',
      status: 'active',
    },
  ],
  'src-zarplata': [
    {
      id: 'zarplata-391029',
      fingerprint: 'zarplata-391029',
      title: 'Senior Python / Django разработчик',
      company: 'Сибирские Цифровые Технологии',
      location: 'Новосибирск / Remote',
      isRemote: true,
      experienceLevel: 'Senior',
      employmentType: 'Full-time',
      salary: { from: 240000, to: 310000, currency: 'RUR', gross: false },
      description: 'Разработка SaaS-платформы промышленной автоматизации и мониторинга IoT-устройств. Мы ищем сильного Python-разработчика для оптимизации обработки временных рядов данных и построения REST API для аналитических панелей.',
      responsibilities: [
        'Разработка сервисов сбора и анализа телеметрии на Python (Django, FastAPI)',
        'Проектирование схемы данных в PostgreSQL и TimescaleDB для миллионов сенсоров',
        'Оптимизация очередей задач через Celery и Redis',
        'Покрытие кода тестами и интеграция в CI/CD пайплайны',
      ],
      qualifications: [
        'Опыт работы с Python и Django/FastAPI от 4 лет',
        'Уверенные знания SQL, индексации и партиционирования в PostgreSQL',
        'Понимание асинхронного программирования (asyncio) и микросервисных паттернов',
        'Опыт работы с Docker и Docker Compose',
      ],
      niceToHave: [
        'Опыт работы с ClickHouse или TimescaleDB',
        'Знание протоколов MQTT и WebSocket',
      ],
      benefits: [
        'Полная удаленка с гибким началом рабочего дня',
        'Официальное трудоустройство в аккредитованной IT-компании',
        'Компенсация расходов на спорт и обустройство рабочего места',
      ],
      aboutCompany: 'Сибирские Цифровые Технологии — аккредитованная IT-компания, специализирующаяся на разработке IoT и AI решений для промышленности.',
      contactInfo: 'job@siberian-digital.ru',
      requiredSkills: ['Python', 'Django', 'FastAPI', 'PostgreSQL', 'Docker', 'Celery', 'TimescaleDB'],
      url: 'https://zarplata.ru/vacancy/391029',
      provenance: { sourceType: 'rss', sourceId: 'src-zarplata', sourceUrl: 'https://zarplata.ru', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-16T18:00:00.000Z',
      status: 'active',
    },
  ],
  'src-trudvsem': [
    {
      id: 'trudvsem-819201',
      fingerprint: 'trudvsem-819201',
      title: 'Ведущий специалист по информационной безопасности',
      company: 'Государственный Дата-Центр',
      location: 'Москва / Казань',
      isRemote: false,
      experienceLevel: 'Senior',
      employmentType: 'Full-time',
      salary: { from: 220000, to: 290000, currency: 'RUR', gross: true },
      description: 'Обеспечение комплексной информационной безопасности регионального дата-центра и государственных информационных систем. Мониторинг инцидентов, аудит уязвимостей и защита каналов связи.',
      responsibilities: [
        'Эксплуатация и настройка SIEM-систем, WAF и межсетевых экранов нового поколения (NGFW)',
        'Расследование инцидентов ИБ и координация реагирования на кибератаки',
        'Проведение сканирования уязвимостей и контроль их устранения командами разработки',
        'Подготовка документации по требованиям регуляторов (ФСТЭК, ФСБ, 187-ФЗ КИИ)',
      ],
      qualifications: [
        'Высшее профильное образование в сфере информационной безопасности',
        'Опыт работы в ИБ или SOC от 3 лет',
        'Знание нормативной базы (152-ФЗ, 187-ФЗ, приказы ФСТЭК №17, №21)',
        'Практический опыт анализа сетевого трафика (Wireshark, tcpdump)',
      ],
      niceToHave: [
        'Сертификаты CEH, OSCP, CISSP или отечественные курсы по защите КИИ',
      ],
      benefits: [
        'Стабильная государственная служба и статус аккредитованной IT-организации',
        'Льготная IT-ипотека и отсрочка',
        'Квартальные и годовые премии за предотвращение инцидентов',
      ],
      aboutCompany: 'Государственный Дата-Центр обеспечивает бесперебойную работу критически важной цифровой инфраструктуры государственных услуг.',
      contactInfo: 'ib-hr@gov-datacenter.ru',
      requiredSkills: ['Security', 'SIEM', 'Linux', 'Network', 'Compliance', 'Firewall', '187-ФЗ'],
      url: 'https://trudvsem.ru/vacancy/819201',
      provenance: { sourceType: 'rss', sourceId: 'src-trudvsem', sourceUrl: 'https://trudvsem.ru', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-15T11:00:00.000Z',
      status: 'active',
    },
  ],
  'src-weworkremotely': [
    {
      id: 'wwr-772910',
      fingerprint: 'wwr-772910',
      title: 'Senior React / Design Systems Engineer',
      company: 'Hotjar',
      location: 'Remote (EU / Americas)',
      isRemote: true,
      experienceLevel: 'Senior',
      employmentType: 'Full-time',
      salary: { from: 110000, to: 145000, currency: 'USD' },
      description: 'Hotjar is looking for a Senior Frontend Engineer to join our Design Systems squad. You will be responsible for creating, documenting, and evolving our accessible, tokenized component library used across all Hotjar product lines by millions of daily users.',
      responsibilities: [
        'Develop and maintain our shared UI component library in React, TypeScript, and Storybook',
        'Ensure WCAG 2.2 AA accessibility compliance across all components with automated testing',
        'Create intuitive APIs for components, facilitating smooth adoption across product squads',
        'Optimize package bundling, tree-shaking, and CSS runtime footprint',
        'Lead architectural discussions around design tokens, theming, and dark mode support',
      ],
      qualifications: [
        '4+ years of professional experience with React, TypeScript, and CSS architecture',
        'Proven expertise building scalable design systems or accessible UI component libraries',
        'Strong knowledge of web accessibility standards (ARIA, semantic HTML, keyboard navigation)',
        'Experience with testing frameworks (Vitest, Testing Library, Playwright)',
      ],
      niceToHave: [
        'Experience with Figma token synchronization tools (Tokens Studio)',
        'Familiarity with Web Components or CSS-in-JS migration strategies',
      ],
      benefits: [
        'Fully remote working environment with flexible working hours',
        '€4,000 holiday budget per year + 40 days of paid leave',
        '€2,000 yearly training budget and company-funded book club',
        'Free home office equipment, ergonomic chair, and high-spec MacBook Pro',
      ],
      aboutCompany: 'Hotjar is a product experience insights platform that gives you behavior analytics and feedback data to understand your customers.',
      contactInfo: 'careers@hotjar.com',
      requiredSkills: ['React', 'TypeScript', 'CSS', 'Storybook', 'Accessibility', 'Figma', 'Playwright'],
      url: 'https://weworkremotely.com/remote-jobs/hotjar-senior-react-design-systems-engineer',
      provenance: { sourceType: 'rss', sourceId: 'src-weworkremotely', sourceUrl: 'https://weworkremotely.com', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-17T13:00:00.000Z',
      status: 'active',
    },
  ],
  'src-remoteok': [
    {
      id: 'remoteok-55102',
      fingerprint: 'remoteok-55102',
      title: 'Head of Data Science / ML Platform',
      company: 'Runway ML',
      location: 'Anywhere in the World',
      isRemote: true,
      experienceLevel: 'Executive',
      employmentType: 'Full-time',
      salary: { from: 180000, to: 240000, currency: 'USD' },
      description: 'Runway is seeking a Head of Data Science & Machine Learning Platform to direct our foundation model training and inference optimization teams. You will oversee the deployment of next-generation multimodal generative AI systems at global scale.',
      responsibilities: [
        'Lead research and engineering squads training video generation and multimodal foundation models',
        'Architect distributed training infrastructure on multi-node GPU clusters (NVIDIA H100/H200)',
        'Optimize model inference latency, quantization, and tensor parallelism (vLLM, TensorRT-LLM)',
        'Establish automated model evaluation benchmarks, safety guardrails, and data pipeline governance',
        'Partner with executive leadership on AI roadmap, computing budget allocation, and hiring',
      ],
      qualifications: [
        '7+ years in machine learning research and engineering with 3+ years managing high-performing teams',
        'Deep expertise in PyTorch, distributed training (DeepSpeed, Megatron-LM), and CUDA acceleration',
        'Proven track record of shipping generative AI models or computer vision systems to production',
        'Ph.D. or Master’s in Computer Science, Machine Learning, or related quantitative discipline',
      ],
      niceToHave: [
        'Top-tier conference publications (NeurIPS, CVPR, ICML, ICLR)',
        'Experience building developer-facing AI APIs and SDKs',
      ],
      benefits: [
        'Work from anywhere on Earth with flexible scheduling',
        'Significant equity grant in one of the fastest-growing generative AI leaders',
        'Comprehensive worldwide health coverage and mental wellness stipends',
        'Unlimited compute access for personal research and exploration',
      ],
      aboutCompany: 'Runway is an applied AI research company building the next generation of creative tools powered by artificial intelligence.',
      contactInfo: 'ai-careers@runwayml.com',
      requiredSkills: ['Python', 'PyTorch', 'Machine Learning', 'LLMs', 'MLOps', 'CUDA', 'DeepSpeed', 'Distributed Systems'],
      url: 'https://remoteok.com/remote-jobs/remote-head-of-data-science-runway-ml',
      provenance: { sourceType: 'rss', sourceId: 'src-remoteok', sourceUrl: 'https://remoteok.com', observedAt: new Date().toISOString() },
      publishedAt: '2026-08-16T19:00:00.000Z',
      status: 'active',
    },
  ],
};
