import type { VacancySourceHealth } from '../domain/vacancy';

export type VacancySourceHealthStatus =
  | 'not_checked'
  | 'healthy'
  | 'degraded'
  | 'unavailable'
  | 'official_access_required';

export const SOURCE_REGISTRY = [
  {
    id: 'hh',
    name: 'hh.ru',
    market: 'Россия и СНГ',
    category: 'Агрегаторы и API',
    transport: 'official_api',
    searchCoverage: 'Полный результат официального поиска в пределах API',
    attributionUrl: 'https://hh.ru/',
    documentationUrl: 'https://api.hh.ru/openapi/redoc',
    reviewedAt: '2026-08-17',
  },
  {
    id: 'remotive',
    name: 'Remotive',
    market: 'Международный remote',
    category: 'Международные площадки',
    transport: 'public_api',
    searchCoverage: 'Глобальные IT и продуктовые вакансии со всего мира',
    attributionUrl: 'https://remotive.com/',
    documentationUrl: 'https://remotive.com/remote-jobs/api',
    reviewedAt: '2026-08-17',
  },
  {
    id: 'src-habr-career',
    name: 'Хабр Карьера',
    market: 'Россия / Удаленка',
    category: 'Агрегаторы и API',
    transport: 'rss_feed',
    searchCoverage: 'Проверенные IT-вакансии от технологических компаний РФ',
    attributionUrl: 'https://career.habr.com/',
    documentationUrl: 'https://career.habr.com/vacancies/rss',
    reviewedAt: '2026-08-17',
  },
  {
    id: 'src-superjob',
    name: 'SuperJob',
    market: 'Россия и СНГ',
    category: 'Агрегаторы и API',
    transport: 'public_api',
    searchCoverage: 'Вакансии крупных корпоративных и технологических работодателей',
    attributionUrl: 'https://superjob.ru/',
    documentationUrl: 'https://api.superjob.ru',
    reviewedAt: '2026-08-17',
  },
  {
    id: 'src-zarplata',
    name: 'Зарплата.ру',
    market: 'Регионы РФ & Remote',
    category: 'Агрегаторы и API',
    transport: 'public_api',
    searchCoverage: 'Региональные IT и управляющие позиции',
    attributionUrl: 'https://zarplata.ru/',
    documentationUrl: 'https://zarplata.ru/api',
    reviewedAt: '2026-08-17',
  },
  {
    id: 'src-trudvsem',
    name: 'Работа в России (ТрудВсем)',
    market: 'Госсектор & РФ',
    category: 'Агрегаторы и API',
    transport: 'open_data',
    searchCoverage: 'Официальный общероссийский банк вакансий',
    attributionUrl: 'https://trudvsem.ru/',
    documentationUrl: 'https://opendata.trudvsem.ru',
    reviewedAt: '2026-08-17',
  },
  {
    id: 'src-weworkremotely',
    name: 'We Work Remotely',
    market: 'Global Remote',
    category: 'Международные площадки',
    transport: 'rss_feed',
    searchCoverage: 'Крупнейшее сообщество удаленной работы в мире',
    attributionUrl: 'https://weworkremotely.com/',
    documentationUrl: 'https://weworkremotely.com/categories/remote-programming-jobs.rss',
    reviewedAt: '2026-08-17',
  },
  {
    id: 'src-remoteok',
    name: 'RemoteOK',
    market: 'Global Remote',
    category: 'Международные площадки',
    transport: 'public_api',
    searchCoverage: 'Технологические стартапы и AI компании',
    attributionUrl: 'https://remoteok.com/',
    documentationUrl: 'https://remoteok.com/api',
    reviewedAt: '2026-08-17',
  },
  {
    id: 'src-tg-itjobs',
    name: 'Telegram @it_jobs',
    market: 'IT Вакансии',
    category: 'Telegram каналы',
    transport: 'telegram_feed',
    searchCoverage: 'Свежие предложения для Senior/Lead разработчиков',
    attributionUrl: 'https://t.me/it_jobs',
    documentationUrl: 'https://t.me/s/it_jobs',
    reviewedAt: '2026-08-17',
  },
  {
    id: 'src-tg-tproger',
    name: 'Telegram @tproger_jobs',
    market: 'Типичный Программист',
    category: 'Telegram каналы',
    transport: 'telegram_feed',
    searchCoverage: 'Подборки IT-вакансий от издания Tproger',
    attributionUrl: 'https://t.me/tproger_jobs',
    documentationUrl: 'https://t.me/s/tproger_jobs',
    reviewedAt: '2026-08-17',
  },
  {
    id: 'src-tg-react',
    name: 'Telegram @job_react',
    market: 'React & Frontend',
    category: 'Telegram каналы',
    transport: 'telegram_feed',
    searchCoverage: 'Frontend, React, Next.js, Vue, WebGL вакансии',
    attributionUrl: 'https://t.me/job_react',
    documentationUrl: 'https://t.me/s/job_react',
    reviewedAt: '2026-08-17',
  },
  {
    id: 'src-tg-backend',
    name: 'Telegram @forphptut (Backend)',
    market: 'Backend & Highload',
    category: 'Telegram каналы',
    transport: 'telegram_feed',
    searchCoverage: 'Node.js, Go, Python, Java, Rust, Архитектура',
    attributionUrl: 'https://t.me/forphptut',
    documentationUrl: 'https://t.me/s/forphptut',
    reviewedAt: '2026-08-17',
  },
  {
    id: 'src-tg-devops',
    name: 'Telegram @devops_jobs',
    market: 'DevOps & SRE',
    category: 'Telegram каналы',
    transport: 'telegram_feed',
    searchCoverage: 'Kubernetes, Cloud, Linux, CI/CD, Terraform',
    attributionUrl: 'https://t.me/devops_jobs',
    documentationUrl: 'https://t.me/s/devops_jobs',
    reviewedAt: '2026-08-17',
  },
  {
    id: 'src-tg-qa',
    name: 'Telegram @qa_jobs',
    market: 'QA & Testing',
    category: 'Telegram каналы',
    transport: 'telegram_feed',
    searchCoverage: 'SDET, Automation, Performance, Manual QA',
    attributionUrl: 'https://t.me/qa_jobs',
    documentationUrl: 'https://t.me/s/qa_jobs',
    reviewedAt: '2026-08-17',
  },
  {
    id: 'src-tg-product',
    name: 'Telegram @product_jobs',
    market: 'Product & Management',
    category: 'Telegram каналы',
    transport: 'telegram_feed',
    searchCoverage: 'CPO, Head of Product, Product Managers',
    attributionUrl: 'https://t.me/product_jobs',
    documentationUrl: 'https://t.me/s/product_jobs',
    reviewedAt: '2026-08-17',
  },
  {
    id: 'src-tg-datascience',
    name: 'Telegram @datasciencejobs',
    market: 'Data Science & AI',
    category: 'Telegram каналы',
    transport: 'telegram_feed',
    searchCoverage: 'LLM, CV, NLP, Data Engineering, MLOps',
    attributionUrl: 'https://t.me/datasciencejobs',
    documentationUrl: 'https://t.me/s/datasciencejobs',
    reviewedAt: '2026-08-17',
  },
  {
    id: 'src-tg-relocate',
    name: 'Telegram @relocate_today',
    market: 'Релокация & EU/US/UAE',
    category: 'Telegram каналы',
    transport: 'telegram_feed',
    searchCoverage: 'Вакансии с визовой поддержкой и релокацией',
    attributionUrl: 'https://t.me/relocate_today',
    documentationUrl: 'https://t.me/s/relocate_today',
    reviewedAt: '2026-08-17',
  },
  {
    id: 'src-tg-gamedev',
    name: 'Telegram @gamedevjob',
    market: 'Gamedev & 3D',
    category: 'Telegram каналы',
    transport: 'telegram_feed',
    searchCoverage: 'Unity, Unreal Engine, C++, Game Design',
    attributionUrl: 'https://t.me/gamedevjob',
    documentationUrl: 'https://t.me/s/gamedevjob',
    reviewedAt: '2026-08-17',
  },
] as const;

export function vacancySourceRegistryView(health: VacancySourceHealth[]) {
  const healthBySource = new Map(health.map((item) => [item.source, item]));
  return SOURCE_REGISTRY.map((source) => ({
    ...source,
    health: healthBySource.get(source.id) ?? {
      status: 'not_checked' as const,
      lastAttemptAt: null,
      lastSuccessAt: null,
      lastErrorCode: null,
      retryAfterAt: null,
      consecutiveFailures: 0,
    },
  }));
}
