import { join } from 'node:path';
import AxeBuilder from '@axe-core/playwright';
import { expect, test, type Page } from '@playwright/test';
import { captureCareerHarness } from './helpers/capture-career-harness';

const CANDIDATE = {
  username: 'qa.candidate',
  email: 'qa.candidate@example.test',
  displayName: 'QA Candidate',
  role: 'candidate' as const,
  candidateId: 'candidate-c37',
};

const ACCOUNT = {
  username: CANDIDATE.username,
  email: CANDIDATE.email,
  displayName: CANDIDATE.displayName,
  profile: {
    headline: '',
    location: '',
    workMode: 'hybrid',
    updatedAt: '2026-09-26T00:00:00.000Z',
  },
  sessions: [],
};

const SNAPSHOT = {
  candidate: {
    id: CANDIDATE.candidateId,
    dataClass: 'synthetic',
    locale: 'ru-RU',
    createdAt: '2026-09-26T00:00:00.000Z',
  },
  messages: [],
  memory: [],
  turns: [],
  dossier: {
    sections: [],
    confirmedCount: 0,
    proposedCount: 0,
    readiness: { complete: false, unresolvedQuestions: 0, checks: [] },
  },
  documents: [],
  assessments: [],
  germanyMarket: null,
  vacancySubscriptions: [],
};

const PARSED_RESUME = {
  targetRole: 'VP of Operations',
  contact: { location: 'Dubai', links: [] },
  experience: [
    {
      title: 'VP of Operations',
      employer: 'Example Co',
      current: true,
      responsibilities: ['Led regional operations'],
      achievements: ['Expanded into four markets'],
    },
  ],
  skills: ['Operations'],
  education: [],
  courses: [],
  tests: [],
  recommendations: [],
  languages: [],
  rawText: 'VP of Operations. Led regional operations. Expanded into four markets.',
};

const MODEL_ROLE = {
  id: 'ops.vp',
  title: 'VP of Operations',
  titleRu: 'Вице-президент по операциям',
  level: 'vp',
  kind: 'primary',
  reason: 'Опыт управления региональными операциями.',
  evidenceRefs: ['memory:fact-1'],
  evidence: ['Руководил операциями в четырёх регионах.'],
};

function campaign(
  origin: 'profile' | 'model' | 'explicit',
  roles = origin === 'model' ? [MODEL_ROLE] : [],
) {
  return {
    roles: {
      value: origin === 'profile' ? ['VP of Operations'] : roles.map((role) => role.title),
      origin,
    },
    regions: { value: ['mena'], origin: 'profile' },
    remoteOnly: false,
    // Сервер отдаёт время автонабора; онбординг принимает только набор новее запроса пересборки.
    autoGeneratedAt: roles.length > 0 && origin === 'model' ? '2026-09-27T10:00:00.000Z' : null,
    autoRoles: roles,
    divergence: { roles: null, regions: null },
  };
}

async function stubFirstLogin(page: Page, options: { startAnonymous?: boolean } = {}) {
  let workspace: unknown = null;
  let rebuildRequested = false;
  let campaignReads = 0;
  let campaignSave: { roles: readonly unknown[]; regions: readonly string[] } | undefined;
  let savedCampaign = campaign('profile', []);
  let userSession: typeof CANDIDATE | null = options.startAnonymous ? null : CANDIDATE;

  await page.route('**/api/v1/**', async (route) => {
    const request = route.request();
    const pathname = new URL(request.url()).pathname;
    if (pathname === '/api/v1/auth/me') return route.fulfill({ json: { data: userSession } });
    if (pathname === '/api/v1/auth/register' && request.method() === 'POST') {
      const body = (request.postDataJSON() as Record<string, string>) ?? {};
      userSession = {
        ...CANDIDATE,
        displayName: body.displayName || CANDIDATE.displayName,
        email: body.email || CANDIDATE.email,
      };
      return route.fulfill({ json: { data: userSession } });
    }
    if (pathname === '/api/v1/account')
      return route.fulfill({ json: { data: userSession ? ACCOUNT : null } });
    if (pathname === '/api/v1/candidate/me')
      return route.fulfill({ json: { data: userSession ? SNAPSHOT : null } });
    if (pathname === '/api/v1/candidate/connections') return route.fulfill({ json: { data: [] } });
    if (pathname === '/api/v1/candidate/workspace' && request.method() === 'GET') {
      return route.fulfill({ json: { data: workspace } });
    }
    if (pathname === '/api/v1/candidate/workspace' && request.method() === 'PUT') {
      workspace = request.postDataJSON()?.workspace ?? null;
      return route.fulfill({ json: { data: workspace } });
    }
    if (pathname === '/api/v1/candidate/resume/import' && request.method() === 'POST') {
      return route.fulfill({
        json: { data: { parsed: PARSED_RESUME, resume: {}, structuredBy: 'rules', factCount: 6 } },
      });
    }
    if (pathname === '/api/v1/candidate/campaign/roles/rebuild' && request.method() === 'POST') {
      rebuildRequested = true;
      campaignReads = 0;
      return route.fulfill({ status: 202, json: { data: { status: 'queued' } } });
    }
    if (pathname === '/api/v1/candidate/campaign' && request.method() === 'GET') {
      if (!rebuildRequested) return route.fulfill({ json: { data: campaign('profile', []) } });
      campaignReads += 1;
      return route.fulfill({ json: { data: campaign(campaignReads === 1 ? 'profile' : 'model') } });
    }
    if (pathname === '/api/v1/candidate/campaign' && request.method() === 'POST') {
      campaignSave = request.postDataJSON();
      const roleTitles =
        campaignSave?.roles.map((role) =>
          typeof role === 'string' ? role : (role as { title: string }).title,
        ) ?? [];
      savedCampaign = {
        ...campaign('explicit', []),
        roles: { value: roleTitles, origin: 'explicit' },
        regions: { value: campaignSave?.regions ?? [], origin: 'explicit' },
      };
      return route.fulfill({ json: { data: savedCampaign } });
    }
    if (pathname === '/api/v1/candidate/matched-vacancies') {
      return route.fulfill({
        json: {
          data: [
            {
              cluster: {
                id: 'c-1',
                canonicalTitle: 'VP of Operations',
                canonicalCompany: 'Scale Corp',
                canonicalLocation: 'Dubai',
                isRemote: true,
                salary: { from: 15000, to: 20000, currency: 'USD', gross: true },
                descriptionSummary: 'Operational leadership across 4 markets',
                skills: ['Operations'],
                primaryUrl: 'https://example.com/vacancy-1',
                sources: [
                  {
                    sourceType: 'hh',
                    sourceId: 'c-1',
                    sourceName: 'hh.ru',
                    sourceUrl: 'https://hh.ru/vacancy/1',
                    observedAt: '2026-09-20T08:00:00.000Z',
                  },
                ],
                firstObservedAt: '2026-09-20T08:00:00.000Z',
                lastSeenAt: '2026-09-23T08:00:00.000Z',
                status: 'active',
                vacanciesCount: 1,
              },
              explanation: {
                clusterId: 'c-1',
                roleMatch: 'target',
                levelMatch: 'match',
                outsideGeography: false,
                matchingPoints: ['Operations'],
                missingPoints: [],
                summary: 'Direct role match',
                calculatedAt: '2026-09-24T08:00:00.000Z',
              },
            },
          ],
          meta: {
            total: 1,
            nextOffset: null,
            campaign: savedCampaign,
            candidateLevel: 'vp',
          },
        },
      });
    }
    if (pathname === '/api/v1/candidate/visits' && request.method() === 'POST') {
      return route.fulfill({ json: { data: { since: null } } });
    }
    return route.fulfill({ json: { data: null } });
  });

  return {
    savedCampaign: () => campaignSave,
    modelRebuildRequested: () => rebuildRequested,
    campaignReadCount: () => campaignReads,
    getUserSession: () => userSession,
  };
}

async function openNewCandidate(page: Page): Promise<void> {
  await page.goto('/app', { waitUntil: 'domcontentloaded' });
  await expect(page.locator('#root')).not.toHaveAttribute('aria-busy', /.*/);
  await expect(page.getByRole('heading', { name: 'С чем разбираемся?' })).toBeVisible();
}

test.describe('B249 first selection onboarding', () => {
  test('waits for model roles, saves the confirmed campaign and opens vacancies', async ({
    page,
  }, testInfo) => {
    const startedAt = Date.now();
    const api = await stubFirstLogin(page);
    await openNewCandidate(page);

    await page.getByRole('button', { name: 'Нет PDF под рукой — вставить текст резюме' }).click();
    await page
      .getByLabel('Опыт, проекты или фрагмент резюме')
      .fill(
        'VP of Operations\nSummary\nLed regional operations for four markets. Managed a team of twenty.',
      );
    await page.getByRole('button', { name: 'Продолжить', exact: true }).click();
    await page.getByRole('button', { name: 'Продолжить', exact: true }).click();
    await page.getByRole('button', { name: 'Продолжить', exact: true }).click();

    await expect(page.getByText('Запрос отправлен модели')).toBeVisible();
    const role = page.getByRole('button', { name: /Вице-президент по операциям/ });
    await expect(role).toHaveAttribute('aria-pressed', 'true');
    await expect(role).toContainText('Гипотеза модели');
    await expect(role).toContainText('Уровень: VP');
    await expect(role).toContainText('управления региональными операциями');
    await expect(role).toContainText('Руководил операциями в четырёх регионах.');
    const accessibility = await new AxeBuilder({ page }).analyze();
    expect(
      accessibility.violations.filter((violation) =>
        ['critical', 'serious'].includes(violation.impact ?? ''),
      ),
    ).toEqual([]);
    await page.screenshot({
      path: testInfo.outputPath('onboarding-model-confirmation.png'),
      fullPage: true,
    });
    await captureCareerHarness(page, testInfo.outputPath('onboarding-model-confirmation.html'));

    if (testInfo.project.name === 'desktop-1440') {
      const originalViewport = page.viewportSize();
      await page.setViewportSize({ width: 280, height: 844 });
      const overflow = await page.evaluate(
        () => document.documentElement.scrollWidth - document.documentElement.clientWidth,
      );
      expect(overflow).toBeLessThanOrEqual(1);
      if (originalViewport) await page.setViewportSize(originalViewport);
    }

    await page.getByRole('button', { name: 'Добавить роль', exact: true }).click();
    await page.getByLabel('Новая роль').fill('Operations Director');
    await page.getByRole('button', { name: 'Добавить', exact: true }).click();
    await page.getByRole('button', { name: 'EU', exact: true }).click();
    await page.getByRole('button', { name: 'Продолжить', exact: true }).click();

    await expect(page.getByRole('heading', { name: 'Первая подборка готова' })).toBeVisible();
    expect(api.modelRebuildRequested()).toBe(true);
    expect(api.campaignReadCount()).toBeGreaterThanOrEqual(2);
    expect(api.savedCampaign()).toMatchObject({
      roles: [{ id: 'ops.vp', title: 'VP of Operations' }, 'Operations Director'],
      regions: ['mena', 'eu'],
    });

    await page.getByRole('button', { name: 'Перейти в «Вакансии»' }).click();
    await expect(page.getByRole('heading', { name: 'Вакансии', level: 1 })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Для подбора не выбрана роль' })).toHaveCount(0);
    const elapsedMs = Date.now() - startedAt;
    console.log(`C37 mocked-model first-selection elapsed_ms=${elapsedMs}`);
    expect(elapsedMs).toBeLessThan(5 * 60 * 1_000);
  });

  test('lets a candidate without a profile start with one role and one region', async ({
    page,
  }, testInfo) => {
    const api = await stubFirstLogin(page);
    await openNewCandidate(page);

    await page.locator('.career-onboarding-source-card', { hasText: 'Расскажу сам' }).click();
    await page.getByRole('button', { name: 'Продолжить', exact: true }).click();
    await expect(page.getByLabel('На какую роль ищете работу?')).toBeVisible();
    await page.getByLabel('На какую роль ищете работу?').fill('Аналитик данных');
    await page.getByRole('button', { name: 'Россия', exact: true }).click();
    await page.screenshot({
      path: testInfo.outputPath('onboarding-quick-start.png'),
      fullPage: true,
    });
    await page.getByRole('button', { name: 'Продолжить', exact: true }).click();

    await expect(page.getByRole('heading', { name: 'Первая подборка готова' })).toBeVisible();
    expect(api.modelRebuildRequested()).toBe(false);
    expect(api.savedCampaign()).toMatchObject({ roles: ['Аналитик данных'], regions: ['ru'] });

    await page.getByRole('button', { name: 'Перейти в «Вакансии»' }).click();
    await expect(page.getByRole('heading', { name: 'Вакансии', level: 1 })).toBeVisible();
    await expect(page.getByRole('heading', { name: 'Для подбора не выбрана роль' })).toHaveCount(0);
  });

  test('new candidate journey from registration and PDF import to first selection in under 5 minutes (B249)', async ({
    page,
  }, testInfo) => {
    const startedAt = Date.now();
    const vpSuffix = testInfo.project.name === 'mobile-390' ? '390' : '1440';
    const timings: Record<string, number> = {};

    const takeStepScreenshot = async (stepSlug: string) => {
      await page.screenshot({
        path: `output/playwright/B249/${stepSlug}-${vpSuffix}.png`,
        fullPage: true,
      });
    };

    const recordStep = async (stepName: string, action: () => Promise<void>) => {
      const stepStart = Date.now();
      await action();
      const durationMs = Date.now() - stepStart;
      timings[stepName] = durationMs;
      console.log(`[B249 timing] step="${stepName}" duration=${durationMs}ms`);
    };

    const api = await stubFirstLogin(page, { startAnonymous: true });
    await openNewCandidate(page);

    // Шаг 1: Регистрация нового кандидата
    await recordStep('01-registration', async () => {
      await expect(page.getByRole('heading', { name: 'С чем разбираемся?' })).toBeVisible();
      await takeStepScreenshot('step-01-pre-register');
      await page.getByRole('button', { name: 'Войти' }).click();
      const dialog = page.getByRole('dialog', { name: 'Аккаунт' });
      await expect(dialog).toBeVisible();
      await dialog.getByRole('button', { name: 'Создать аккаунт' }).click();
      await dialog.getByLabel('Как к вам обращаться').fill('Мария Ковалёва');
      await dialog.getByLabel('Email').fill('maria.kovaleva@example.test');
      await dialog.getByLabel('Пароль').fill('test-passphrase-2026');
      await dialog.locator('#account-legal-consent').check();
      await dialog.getByRole('button', { name: 'Создать и начать' }).click();
      await expect(dialog).toHaveCount(0);
      await expect(page.getByRole('heading', { name: 'С чем разбираемся?' })).toBeVisible();
      await takeStepScreenshot('step-01-registered');
    });

    // Шаг 2: Загрузка PDF резюме
    await recordStep('02-pdf-import', async () => {
      const pdfPath = join(
        process.cwd(),
        'src/features/workspace/fixtures/linkedin-owner-profile.pdf',
      );
      const fileInput = page.locator('.career-file-button input[type="file"]');
      await fileInput.setInputFiles(pdfPath);
      // Ожидаем завершения разбора PDF
      await expect(page.locator('.career-file-button')).not.toContainText('Разбираем резюме…', {
        timeout: 20_000,
      });
      await expect(page.locator('.career-file-button')).toContainText(
        /linkedin-owner-profile\.pdf|\d+\s*стр\./i,
      );
      // Проверяем видимое и активное следующее действие
      const continueBtn = page.getByRole('button', { name: 'Продолжить', exact: true });
      await expect(continueBtn).toBeVisible();
      await expect(continueBtn).toBeEnabled();
      await takeStepScreenshot('step-02-pdf-uploaded');
      await continueBtn.click();
    });

    // Шаг 3: Прогресс разбора (счётчики опыта, образования, навыков)
    await recordStep('03-parse-progress', async () => {
      await expect(page.locator('[data-step="progress"]')).toBeVisible();
      const continueBtn = page.getByRole('button', { name: 'Продолжить', exact: true });
      await expect(continueBtn).toBeVisible();
      await expect(continueBtn).toBeEnabled();
      await takeStepScreenshot('step-03-parse-progress');
      await continueBtn.click();
    });

    // Шаг 4: Проверка фактов профиля
    await recordStep('04-profile-review', async () => {
      await expect(page.locator('[data-step="review"]')).toBeVisible();
      const continueBtn = page.getByRole('button', { name: 'Продолжить', exact: true });
      await expect(continueBtn).toBeVisible();
      await expect(continueBtn).toBeEnabled();
      await takeStepScreenshot('step-04-profile-review');
      await continueBtn.click();
    });

    // Шаг 5: Кампания — роли и регионы (гипотезы модели)
    await recordStep('05-campaign-roles', async () => {
      await expect(page.locator('[data-step="campaign"]')).toBeVisible();
      await expect(page.getByText('Запрос отправлен модели')).toBeVisible();
      const roleBtn = page.getByRole('button', { name: /Вице-президент по операциям/ });
      await expect(roleBtn).toBeVisible({ timeout: 15_000 });
      await expect(roleBtn).toHaveAttribute('aria-pressed', 'true');
      const continueBtn = page.getByRole('button', { name: 'Продолжить', exact: true });
      await expect(continueBtn).toBeVisible();
      await expect(continueBtn).toBeEnabled();
      await takeStepScreenshot('step-05-campaign-roles');
      await continueBtn.click();
    });

    // Шаг 6: Первая подборка готова
    await recordStep('06-done-ready', async () => {
      await expect(page.getByRole('heading', { name: 'Первая подборка готова' })).toBeVisible();
      const vacanciesBtn = page.getByRole('button', { name: 'Перейти в «Вакансии»' });
      await expect(vacanciesBtn).toBeVisible();
      await expect(vacanciesBtn).toBeEnabled();
      await takeStepScreenshot('step-06-done-ready');
      await vacanciesBtn.click();
    });

    // Шаг 7: Экран «Вакансии» с первой подборкой
    await recordStep('07-vacancies-feed', async () => {
      await expect(page.getByRole('heading', { name: 'Вакансии', level: 1 })).toBeVisible();
      await expect(page.getByRole('heading', { name: 'Для подбора не выбрана роль' })).toHaveCount(
        0,
      );
      await takeStepScreenshot('step-07-vacancies-feed');
    });

    const totalElapsedMs = Date.now() - startedAt;
    console.log(
      `[B249 summary ${vpSuffix}] Total time from registration to vacancies: ${totalElapsedMs}ms (${(totalElapsedMs / 1000).toFixed(1)}s)`,
    );
    console.log(`[B249 step breakdown ${vpSuffix}]:`, JSON.stringify(timings, null, 2));

    expect(totalElapsedMs).toBeLessThan(5 * 60 * 1000); // Путь строго меньше 5 минут
    expect(api.modelRebuildRequested()).toBe(true);
    expect(api.savedCampaign()).toBeDefined();
    expect(api.getUserSession()).not.toBeNull();
  });
});
