/**
 * Названия стран и слова, которыми площадки заменяют место работы.
 *
 * B203: карта считает хабы по городам, и страна или «Hybrid» в этом списке
 * раздувает счёт и обещает точку там, где её нет. Правило одно на сервер и на
 * экран, поэтому список живёт в общем слое. Здесь только имена: координаты
 * остаются в справочнике сервера и приписываются лишь там, где измерены.
 */
const COUNTRY_NAMES: ReadonlySet<string> = new Set([
  'нидерланды',
  'netherlands',
  'германия',
  'germany',
  'великобритания',
  'uk',
  'армения',
  'armenia',
  'сербия',
  'serbia',
  'кипр',
  'cyprus',
  'грузия',
  'georgia',
  'оаэ',
  'uae',
  'сша',
  'usa',
  'казахстан',
  'kazakhstan',
  'польша',
  'poland',
  'португалия',
  'portugal',
  'испания',
  'spain',
  'франция',
  'france',
  'argentina',
  'australia',
  'austria',
  'azerbaijan',
  'belarus',
  'belgium',
  'brazil',
  'bulgaria',
  'canada',
  'chile',
  'china',
  'czechia',
  'denmark',
  'estonia',
  'finland',
  'greece',
  'hungary',
  'india',
  'indonesia',
  'ireland',
  'israel',
  'italy',
  'japan',
  'latvia',
  'lithuania',
  'malaysia',
  'mexico',
  'norway',
  'philippines',
  'romania',
  'russia',
  'singapore',
  'sweden',
  'switzerland',
  'thailand',
  'turkey',
  'ukraine',
  'unitedarabemirates',
  'unitedkingdom',
  'unitedstates',
  'uzbekistan',
  'vietnam',
  'австралия',
  'австрия',
  'азербайджан',
  'аргентина',
  'беларусь',
  'бельгия',
  'болгария',
  'бразилия',
  'венгрия',
  'вьетнам',
  'греция',
  'дания',
  'израиль',
  'индия',
  'индонезия',
  'ирландия',
  'италия',
  'канада',
  'китай',
  'латвия',
  'литва',
  'малайзия',
  'мексика',
  'норвегия',
  'россия',
  'румыния',
  'сингапур',
  'таиланд',
  'турция',
  'узбекистан',
  'украина',
  'филиппины',
  'финляндия',
  'чехия',
  'чили',
  'швейцария',
  'швеция',
  'эстония',
  'япония',
]);

function normalizeNameKey(value?: string): string {
  return (value ?? '').toLowerCase().replace(/[^\p{L}\p{N}]/gu, '');
}

export function isCountryName(label?: string): boolean {
  const key = normalizeNameKey(label);
  return key.length > 0 && COUNTRY_NAMES.has(key);
}

/** Надрегиональные ярлыки площадок: местом на карте они не являются. */
const REGION_LABELS: ReadonlySet<string> = new Set([
  'emea',
  'apac',
  'latam',
  'amer',
  'americas',
  'europe',
  'европа',
  'asia',
  'азия',
  'africa',
  'африка',
  'worldwide',
  'global',
  'anywhere',
  'distributed',
  'homeoffice',
  'hybrid',
  'onsite',
  'remote',
  'удалённо',
  'удаленно',
  'гибрид',
]);

export function isRegionLabel(label?: string): boolean {
  const key = normalizeNameKey(label);
  return key.length > 0 && REGION_LABELS.has(key);
}
