import type { MatchedVacancyFacets } from '../../../shared/matchedVacancyFacets';
import type { VacanciesScreenState } from '../vacancies/VacanciesScreenFilters';
import type { MatchedVacancyItem } from './cabinetTypes';
import {
  API_MUTATION_TIMEOUT_MS,
  API_READ_TIMEOUT_MS,
  CoachApiError as CoachApiErrorClass,
  apiRequestSignal,
  apiFetch,
  readData,
  throwApiError,
} from './apiClient';

/**
 * Чтение подбора живёт отдельно от общего API кабинета.
 *
 * Подбор — единственный ответ, который не помещается в один запрос: он едет
 * страницами внутри байтового бюджета (INC-029) и по плану смещений (B211).
 * Держать этот разговор рядом с однократными вызовами кабинета значило бы
 * растить `coachApi.ts` за его же потолок в 800 строк.
 */

/** Роль кампании ниже порога значимости (B247, срез 2) — баннер «Вакансий». */
export interface CampaignRoleHypothesis {
  readonly role: string;
  readonly vacancyCount: number;
  readonly isHypothesis: boolean;
}

export interface CampaignMetaView {
  readonly roles: {
    readonly value: readonly string[];
    readonly origin: 'explicit' | 'model' | 'profile' | 'default';
  };
  readonly regions: {
    readonly value: readonly string[];
    readonly origin: 'explicit' | 'model' | 'profile' | 'default';
  };
  readonly remoteOnly?: boolean;
  readonly autoGeneratedAt?: string | null;
  readonly autoRoles?: readonly {
    readonly id: string;
    readonly title: string;
    readonly titleRu: string;
    readonly level: 'ic' | 'lead' | 'head' | 'vp' | 'c-level' | null;
    readonly kind: 'primary' | 'adjacent';
    readonly reason: string;
    readonly evidenceRefs: readonly string[];
    readonly evidence: readonly string[];
  }[];
  readonly roleHypotheses?: readonly CampaignRoleHypothesis[];
  readonly suggestedRegions?: readonly string[];
}

export interface CandidateCampaignUpdate {
  readonly roles: readonly (string | { readonly id: string; readonly title: string })[];
  readonly regions: readonly string[];
  readonly remoteOnly?: boolean;
}

export interface MatchedVacancyPage {
  readonly facets?: MatchedVacancyFacets;
  readonly items: MatchedVacancyItem[];
  readonly total: number;
  readonly nextOffset: number | null;
  /** Смещения всех страниц пула — приходят только с первой (B211). */
  readonly pageOffsets?: readonly number[];
  /** Кампания и гипотезы роли — приходят только с первой страницей (B248). */
  readonly campaign?: CampaignMetaView;
  /** Целевой уровень кандидата, выведенный сервером (B248) — с первой страницей. */
  readonly candidateLevel?: string | null;
}

/**
 * Подбор приходит страницами: целиком тело в 776 КБ до браузера не доезжало —
 * маршрут обрывал ответ примерно на 20 КБ, и экран ждал его вечно (INC-029).
 */
export async function getMatchedVacancyPage(
  offset = 0,
  signal?: AbortSignal,
  filters?: VacanciesScreenState,
): Promise<MatchedVacancyPage> {
  const response = await apiFetch(
    `/api/v1/candidate/matched-vacancies?${matchedVacancyQuery(offset, filters)}`,
    { signal },
  );
  if (!response.ok) {
    await throwApiError(response);
  }
  const envelope = (await response.json()) as {
    data?: unknown;
    meta?: {
      facets?: MatchedVacancyFacets;
      total?: unknown;
      nextOffset?: unknown;
      pageOffsets?: unknown;
      campaign?: CampaignMetaView;
      candidateLevel?: string | null;
    };
  };
  if (!Array.isArray(envelope.data)) {
    throw new CoachApiErrorClass('Ответ сервиса не разобран.', 'malformed_response', false);
  }
  const items = envelope.data as MatchedVacancyItem[];
  const total = typeof envelope.meta?.total === 'number' ? envelope.meta.total : items.length;
  const nextOffset =
    typeof envelope.meta?.nextOffset === 'number' ? envelope.meta.nextOffset : null;
  // План чтения — это список чисел или ничего: чужой тип на его месте не
  // становится смещениями, иначе чтение попросит страницу по мусору (B211).
  const planned = envelope.meta?.pageOffsets;
  const pageOffsets =
    Array.isArray(planned) && planned.every((entry) => typeof entry === 'number')
      ? (planned as number[])
      : undefined;
  return {
    items,
    ...(envelope.meta?.facets ? { facets: envelope.meta.facets } : {}),
    total,
    nextOffset,
    ...(pageOffsets ? { pageOffsets } : {}),
    ...(envelope.meta?.campaign ? { campaign: envelope.meta.campaign } : {}),
    ...(envelope.meta?.candidateLevel !== undefined
      ? { candidateLevel: envelope.meta.candidateLevel }
      : {}),
  };
}

export function matchedVacancyQuery(offset: number, filters?: VacanciesScreenState): string {
  const query = new URLSearchParams({ offset: String(offset) });
  const groups = [
    ['region', filters?.regions], ['level', filters?.levels],
    ['source', filters?.sources], ['role', filters?.roles],
  ] as const;
  for (const [key, values] of groups) {
    for (const value of values ?? []) query.append(key, value);
  }
  if (filters?.remoteOnly) query.set('remote', '1');
  return query.toString();
}

export async function saveCandidateCampaign(
  input: CandidateCampaignUpdate,
): Promise<CampaignMetaView> {
  const response = await apiFetch('/api/v1/candidate/campaign', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(input),
  });
  return readData<CampaignMetaView>(response);
}

export async function updateCampaignRoles(
  roles: readonly (string | { readonly id: string; readonly title: string })[],
  currentCampaign?: CampaignMetaView,
  signal?: AbortSignal,
): Promise<CampaignMetaView> {
  const base = currentCampaign ?? (await getCandidateCampaign(signal));
  return saveCandidateCampaign({
    roles,
    regions: base.regions.value,
    remoteOnly: base.remoteOnly ?? false,
  });
}

export async function getCandidateCampaign(signal?: AbortSignal): Promise<CampaignMetaView> {
  const response = await apiFetch('/api/v1/candidate/campaign', {
    signal: apiRequestSignal(signal, API_READ_TIMEOUT_MS),
  });
  return readData<CampaignMetaView>(response);
}

export async function rebuildCandidateCampaignRoles(signal?: AbortSignal): Promise<void> {
  const response = await apiFetch('/api/v1/candidate/campaign/roles/rebuild', {
    method: 'POST',
    signal: apiRequestSignal(signal, API_MUTATION_TIMEOUT_MS),
  });
  await readData<{ status: 'queued' }>(response);
}

export async function getMatchedVacancies(signal?: AbortSignal): Promise<MatchedVacancyItem[]> {
  const page = await getMatchedVacancyPage(0, signal);
  return page.items;
}
